/**
 * M1-19 · 商店配置：统一价格表（PokeAPI 道具表没有价格，这里定义）与各商店货架。
 * 价格参照第八世代友好商店；出售价 = 一半。没有列出价格的物品不能买卖（如大师球、重要物品）。
 */
import type { ShopDef } from '@/systems/shop';
import { TM_DEFS, tmItemId } from '@/config/tms';

/** 招式学习器：商店来源的定价（config/tms） */
const TM_PRICES: Record<string, number> = Object.fromEntries(TM_DEFS.flatMap((t) => (t.source.kind === 'shop' ? [[tmItemId(t.move), t.source.price]] : [])));

export const ITEM_PRICES: Readonly<Record<string, number>> = {
  // 精灵球
  'poke-ball': 200,
  'great-ball': 600,
  'ultra-ball': 800,
  'quick-ball': 1000,
  'net-ball': 1000,
  'dusk-ball': 1000,
  // 药品
  potion: 300,
  'super-potion': 700,
  'hyper-potion': 1500,
  antidote: 200,
  'paralyze-heal': 300,
  awakening: 250,
  'burn-heal': 300,
  'ice-heal': 100,
  'full-heal': 400,
  revive: 2000,
  // 树果
  'oran-berry': 80,
  'sitrus-berry': 400,
  'lum-berry': 800,
  'leppa-berry': 300,
  'cheri-berry': 120,
  'chesto-berry': 120,
  'pecha-berry': 120,
  'rawst-berry': 120,
  'aspear-berry': 120,
  'pomeg-berry': 600,
  'kelpsy-berry': 600,
  'qualot-berry': 600,
  'hondew-berry': 600,
  'grepa-berry': 600,
  'tamato-berry': 600,
  'occa-berry': 1000,
  'passho-berry': 1000,
  'wacan-berry': 1000,
  'rindo-berry': 1000,
  'yache-berry': 1000,
  'chople-berry': 1000,
  'razz-berry': 100,
  'figy-berry': 200,
  'wiki-berry': 1200,
  // 采集素材（计划文档 §9.2；只收购，出售价 = 一半）
  'medicinal-herb': 200,
  'fragrant-herb': 600,
  seashell: 400,
  pearl: 2800,
  'tiny-mushroom': 1000,
  'big-mushroom': 5000,
  'glow-mushroom': 3000,
  gravel: 100,
  'hard-ore': 1200,
  honey: 600,
  'growth-mulch': 200,
  'rich-mulch': 200,
  'damp-mulch': 200,
  'surprise-mulch': 400,
  // 进化道具
  'fire-stone': 3000,
  'water-stone': 3000,
  'thunder-stone': 3000,
  'leaf-stone': 3000,
  'sun-stone': 3000,
  'kings-rock': 3000,
  'linking-cord': 3000,
  // 携带物（只收购，市场海货摊卖神秘水滴）
  'mystic-water': 1000,
  charcoal: 1000,
  'miracle-seed': 1000,
  magnet: 1000,
  'sharp-beak': 1000,
  'silver-powder': 1000,
  'poison-barb': 1000,
  'silk-scarf': 1000,
  'black-belt': 1000,
  'soft-sand': 1000,
  'hard-stone': 1000,
  'never-melt-ice': 1000,
  'spell-tag': 1000,
  'twisted-spoon': 1000,
  'dragon-fang': 1000,
  'black-glasses': 1000,
  'metal-coat': 2000,
  'fairy-feather': 1000,
  leftovers: 4000,
  'life-orb': 4000,
  'focus-sash': 4000,
  'expert-belt': 4000,
  'choice-band': 4000,
  'choice-specs': 4000,
  'choice-scarf': 4000,
  // 营养剂
  'hp-up': 10000,
  protein: 10000,
  iron: 10000,
  calcium: 10000,
  zinc: 10000,
  carbos: 10000,
  // 个体值洗练道具
  'reroll-stone': 3000,
  'focus-reroll-stone': 6000,
  'bottle-cap': 50000,
  'gold-bottle-cap': 200000,
  // 重要物品（只能买 1 次，不能出售）
  bicycle: 2000,
  // 招式学习器（可反复使用，每种只能买 1 次）
  ...TM_PRICES,
};

export const SHOPS: readonly ShopDef[] = [
  {
    // 计划文档 §6：港湾大市场卖基础招式学习器（纪念品摊位）
    id: 'harbor-tms',
    name: '阿岚招式摊',
    greeting: '招式学习器！一张能用一辈子！',
    buysBack: false,
    stock: TM_DEFS.flatMap((t) => (t.source.kind === 'shop' && t.source.shop === 'harbor-tms' ? [{ item: tmItemId(t.move), once: true, ...(t.source.badges ? { badges: t.source.badges } : {}) }] : [])),
  },
  {
    id: 'cuilan-mart',
    name: '友好商店',
    greeting: '欢迎光临！请问需要什么？',
    buysBack: true,
    stock: [
      { item: 'poke-ball' },
      { item: 'great-ball', badges: 1 },
      { item: 'ultra-ball', badges: 3 },
      { item: 'potion' },
      { item: 'super-potion', badges: 1 },
      { item: 'hyper-potion', badges: 3 },
      { item: 'antidote' },
      { item: 'paralyze-heal' },
      { item: 'awakening' },
      { item: 'burn-heal' },
      { item: 'ice-heal' },
      { item: 'full-heal', badges: 2 },
      { item: 'revive', badges: 1 },
      // 萌芽镇友好商店独家：自行车（买过后下架）
      { item: 'bicycle', once: true },
      { item: 'growth-mulch', flag: 'breeder-lv3' },
      { item: 'rich-mulch', flag: 'breeder-lv3' },
    ],
  },
  // M3-21 精灵联盟：大厅商店（齐全）与四条回廊的补给台（只卖对战药品，不卖球）
  {
    id: 'league-mart',
    name: '联盟商店',
    greeting: '联盟商店，全翠澜最齐全的对战补给！',
    buysBack: true,
    stock: [
      { item: 'ultra-ball' },
      { item: 'quick-ball' },
      { item: 'hyper-potion' },
      { item: 'super-potion' },
      { item: 'full-heal' },
      { item: 'revive' },
      { item: 'antidote' },
      { item: 'paralyze-heal' },
      { item: 'awakening' },
      { item: 'burn-heal' },
      { item: 'ice-heal' },
    ],
  },
  {
    id: 'league-supply',
    name: '回廊补给台',
    greeting: '补给台：只供应对战药品。',
    buysBack: false,
    stock: [{ item: 'hyper-potion' }, { item: 'super-potion' }, { item: 'full-heal' }, { item: 'revive' }],
  },
  {
    id: 'harbor-tools',
    name: '阿强杂货摊',
    greeting: '出海必备，应有尽有！',
    buysBack: true,
    stock: [
      { item: 'poke-ball' },
      { item: 'great-ball' },
      { item: 'net-ball' },
      { item: 'dusk-ball' },
      { item: 'quick-ball', badges: 1 },
      // 营养剂（拿到第 1 枚徽章后上架）
      { item: 'hp-up', badges: 1 },
      { item: 'protein', badges: 1 },
      { item: 'iron', badges: 1 },
      { item: 'calcium', badges: 1 },
      { item: 'zinc', badges: 1 },
      { item: 'carbos', badges: 1 },
      // 个体值洗练（第 1 枚徽章后上架；王冠价高）
      { item: 'reroll-stone', badges: 1 },
      { item: 'focus-reroll-stone', badges: 1 },
      { item: 'bottle-cap', badges: 1 },
      { item: 'gold-bottle-cap', badges: 1 },
      { item: 'potion' },
      { item: 'super-potion' },
      { item: 'full-heal', badges: 1 },
    ],
  },
  {
    id: 'harbor-fruit',
    name: '老吴果摊',
    greeting: '都是今早刚摘的，尝尝看！',
    buysBack: false,
    stock: [
      { item: 'oran-berry' },
      { item: 'sitrus-berry' },
      { item: 'cheri-berry' },
      { item: 'chesto-berry' },
      { item: 'pecha-berry' },
      { item: 'rawst-berry' },
      { item: 'aspear-berry' },
      { item: 'leppa-berry' },
      { item: 'lum-berry', badges: 1 },
      // 计划文档 §9.3 肥料
      // 计划文档 §9.4：肥料按培育家等级上架（3 级 / 6 级）
      { item: 'growth-mulch', flag: 'breeder-lv3' },
      { item: 'rich-mulch', flag: 'breeder-lv3' },
      { item: 'damp-mulch', flag: 'breeder-lv3' },
      { item: 'surprise-mulch', flag: 'breeder-lv6' },
    ],
  },
  {
    id: 'harbor-sea',
    name: '阿美海货摊',
    greeting: '海里捞上来的宝贝，看中哪个？',
    buysBack: true,
    markup: 1.1,
    stock: [{ item: 'mystic-water' }, { item: 'water-stone' }, { item: 'thunder-stone', badges: 1 }, { item: 'kings-rock', badges: 1 }, { item: 'linking-cord', badges: 1 }],
  },
];

export const SHOP_BY_ID: ReadonlyMap<string, ShopDef> = new Map(SHOPS.map((s) => [s.id, s]));
