/**
 * M3-16 · 琉璃群岛道馆训练家（室内固定站位，NPC 定义在 config/npcs/glazeGyms.ts）。
 * 等级按第 1 档设计（44–47）；馆主队伍由 GymDef 动态生成（party 留空）。物种为暂定，M3-28 生态替换。
 */
import type { TrainerDef } from '@/systems/trainers';

const leader = (id: string, name: string, title: string, gym: string, intro: string[], defeat: string[], after: string[]): TrainerDef => ({
  id,
  name,
  title,
  ai: 'smart',
  prizeBase: 0,
  sight: { range: 0, fov: 0 },
  party: [],
  gym,
  intro,
  defeat,
  after,
  entrance: 'bow',
});

export const GLAZE_GYM_TRAINERS: TrainerDef[] = [
  // —— 幻影道馆（超）——
  {
    id: 'gym-mirage-1',
    name: '镜子',
    title: '超能力者',
    ai: 'smart',
    prizeBase: 36,
    sight: { range: 6, fov: 80 },
    party: [
      { species: 343, level: 44, moves: ['psybeam', 'rapid-spin', 'ancient-power', 'cosmic-power'] },
      { species: 79, level: 45, moves: ['psychic', 'water-pulse', 'yawn', 'amnesia'] },
    ],
    intro: ['从镜子里走出来的，是你本人吗？'],
    defeat: ['镜子里的我也输了……'],
    after: ['这一间的两面镜子：一面回大厅，一面通往中厅。', '中厅里那颗水晶球会转动镜子的去向。'],
    entrance: 'wave',
  },
  {
    id: 'gym-mirage-2',
    name: '阿映',
    title: '超能力者',
    ai: 'smart',
    prizeBase: 36,
    sight: { range: 6, fov: 80 },
    party: [
      { species: 120, level: 45, moves: ['psybeam', 'bubble-beam', 'swift', 'recover'] },
      { species: 80, level: 46, moves: ['psychic', 'surf', 'slack-off', 'calm-mind'] },
    ],
    intro: ['东镜这边的路，比西边更深。'],
    defeat: ['看来你已经看穿了。'],
    after: ['后排东厅那面镜子通往后中厅——终点镜就在那里。', '可终点镜只有在水晶球放出金光时才认路。'],
    entrance: 'flex',
  },
  {
    id: 'gym-mirage-3',
    name: '紫菀',
    title: '占卜师',
    ai: 'smart',
    prizeBase: 40,
    sight: { range: 7, fov: 80 },
    party: [
      { species: 344, level: 46, moves: ['psychic', 'earth-power', 'reflect', 'light-screen'] },
      { species: 121, level: 47, moves: ['psychic', 'surf', 'thunderbolt', 'recover'] },
    ],
    intro: ['我已经占卜到了——你会来到这里。', '可我没占卜到结局。'],
    defeat: ['……结局原来是这样。'],
    after: ['幻月馆主的宝石海星很快，先手的招式要留着用。'],
    entrance: 'bow',
  },
  leader(
    'gym-mirage-leader',
    '幻月',
    '幻影道馆馆主',
    'gym-mirage',
    ['我是幻月。幻影镇的雾里，总有人看见不存在的东西。', '你一路穿过了那么多面镜子——那么，此刻站在我面前的，是真正的你吗？', '让我看看你内心的倒影！'],
    ['……倒影碎了，而你还站着。'],
    ['镜子不会骗人，骗人的是看镜子的人。', '去幽魄的墓厅吧，那里比这里更暗。'],
  ),
  // —— 幽冥道馆（鬼）——
  {
    id: 'gym-ghost-1',
    name: '阿烛',
    title: '守墓人',
    ai: 'smart',
    prizeBase: 36,
    sight: { range: 5, fov: 80 },
    party: [
      { species: 92, level: 44, moves: ['hex', 'hypnosis', 'sludge-bomb', 'confuse-ray'] },
      { species: 769, level: 45, moves: ['shadow-ball', 'earth-power', 'iron-defense', 'giga-drain'] },
    ],
    intro: ['嘘——别吵醒长明灯。'],
    defeat: ['灯……还亮着吧？'],
    after: ['西翼的长明灯点亮之后，就会一直亮着。', '中廊的灵火要两盏光才能驱散：烛台照中廊，再加上西翼这盏。'],
    entrance: 'bow',
  },
  {
    id: 'gym-ghost-2',
    name: '小幽',
    title: '灵媒',
    ai: 'smart',
    prizeBase: 36,
    sight: { range: 5, fov: 80 },
    party: [
      { species: 93, level: 45, moves: ['shadow-ball', 'sludge-bomb', 'hypnosis', 'dream-eater'] },
      { species: 864, level: 46, moves: ['hex', 'giga-drain', 'will-o-wisp', 'ancient-power'] },
    ],
    intro: ['东翼的灵火，是我们最古老的看守。'],
    defeat: ['它们不再看守你了。'],
    after: ['最后一道灵火怕的是东翼的长明灯。'],
    entrance: 'wave',
  },
  {
    id: 'gym-ghost-3',
    name: '墨夜',
    title: '灵媒',
    ai: 'smart',
    prizeBase: 40,
    sight: { range: 6, fov: 80 },
    party: [
      { species: 770, level: 46, moves: ['shadow-ball', 'earth-power', 'giga-drain', 'iron-defense'] },
      { species: 94, level: 47, moves: ['shadow-ball', 'sludge-bomb', 'thunderbolt', 'hypnosis'] },
    ],
    intro: ['走到这里的人，都是三盏灯点对了的人。'],
    defeat: ['……你的灯火真亮。'],
    after: ['恶属性和幽灵属性的招式对馆主的伙伴效果拔群。', '小心耿鬼的催眠术。'],
    entrance: 'flex',
  },
  leader(
    'gym-ghost-leader',
    '幽魄',
    '幽冥道馆馆主',
    'gym-ghost',
    ['……你身后跟着的，是长明灯的光。我是幽魄。', '彩幽市的老人说，琉璃群岛的海底睡着一座神殿，亡灵们一直在守着它。', '在黑暗里，你还看得清你的伙伴吗？'],
    ['……灯火不灭。我认输。'],
    ['神殿的门要从海底打开。', '琉璃镇的琉璃馆主，也许知道潜水的办法。'],
  ),
  // —— 琉璃道馆（水）——
  {
    id: 'gym-glaze-1',
    name: '阿澜',
    title: '泳者',
    ai: 'smart',
    prizeBase: 36,
    sight: { range: 6, fov: 80 },
    party: [
      { species: 72, level: 44, moves: ['bubble-beam', 'acid', 'wrap', 'supersonic'] },
      { species: 90, level: 45, moves: ['icicle-spear', 'water-pulse', 'protect', 'iron-defense'] },
    ],
    intro: ['阀门转一下，整个池子的水都会变！'],
    defeat: ['被水冲走了……'],
    after: ['水位高的时候木筏浮起来，水位低的时候栈道露出来。', '每座石岛上都有阀门，别怕走错。'],
    entrance: 'wave',
  },
  {
    id: 'gym-glaze-2',
    name: '小汐',
    title: '泳者',
    ai: 'smart',
    prizeBase: 36,
    sight: { range: 6, fov: 80 },
    party: [
      { species: 222, level: 45, moves: ['bubble-beam', 'ancient-power', 'recover', 'mirror-coat'] },
      { species: 55, level: 46, moves: ['surf', 'psychic', 'ice-beam', 'calm-mind'] },
    ],
    intro: ['东北角那座小岛？那是给不认真的人准备的！'],
    defeat: ['……你很认真。'],
    after: ['从这里坐木筏南下，要先把水位放高。'],
    entrance: 'flex',
  },
  {
    id: 'gym-glaze-3',
    name: '浪花',
    title: '潜水员',
    ai: 'smart',
    prizeBase: 40,
    sight: { range: 6, fov: 80 },
    party: [
      { species: 342, level: 46, moves: ['crabhammer', 'crunch', 'swords-dance', 'aqua-jet'] },
      { species: 62, level: 47, moves: ['waterfall', 'brick-break', 'hypnosis', 'body-slam'] },
    ],
    intro: ['我可是能潜到海底的人！'],
    defeat: ['浮、浮上来了……'],
    after: ['琉璃馆主的蚊香蛙皇会招来雨天，水招会变得更强。', '电属性和草属性的招式会好用很多。'],
    entrance: 'bow',
  },
  leader(
    'gym-glaze-leader',
    '琉璃',
    '琉璃道馆馆主',
    'gym-glaze',
    ['欢迎来到玻璃穹顶。我是琉璃——和这座小镇同名。', '琉璃要经过千百度的火，再沉进冷水里，才能这么透亮。', '你的伙伴们，也经得起这样的淬炼吗？'],
    ['……清澈见底。是你赢了。'],
    ['海底神殿的大门，就在镇子东边的海里。', '等你学会了潜水，就去看看吧。'],
  ),
];
