/**
 * M3-15 · 雷鸣群岛道馆训练家（室内固定站位，NPC 定义在 config/npcs/thunderGyms.ts）。
 * 等级按第 1 档设计（31–34）；馆主队伍由 GymDef 动态生成（party 留空）。野外训练家在 M3-24 / M3-28 加入。
 */
import type { TrainerDef } from '@/systems/trainers';

export const THUNDER_GYM_TRAINERS: TrainerDef[] = [
  // —— 雷鸣道馆（电）——
  {
    id: 'gym-thunder-1',
    name: '阿伏',
    title: '电工',
    ai: 'smart',
    prizeBase: 30,
    sight: { range: 6, fov: 80 },
    party: [
      { species: 25, level: 31, moves: ['spark', 'quick-attack', 'thunder-wave', 'double-team'] },
      { species: 121, level: 32, moves: ['thunderbolt', 'rapid-spin', 'swift', 'recover'] },
    ],
    intro: ['东道的电闸是我看守的！', '想过去？先让我的伙伴给你充充电！'],
    defeat: ['跳、跳闸了……'],
    after: ['电属性怕地面属性——地面系对电招完全免疫。', '入口那根拉杆管着东西两道的电栅；中间那条路，要东西两边的拉杆都接通才开。'],
    entrance: 'flex',
  },
  {
    id: 'gym-thunder-2',
    name: '小铜',
    title: '电工',
    ai: 'smart',
    prizeBase: 30,
    sight: { range: 6, fov: 80 },
    party: [
      { species: 172, level: 31, moves: ['thunder-shock', 'sweet-kiss', 'nasty-plot', 'charm'] },
      { species: 26, level: 32, moves: ['spark', 'iron-tail', 'quick-attack', 'thunder-wave'] },
    ],
    intro: ['西道这边的线路，可是我一根根接起来的！'],
    defeat: ['短路了……'],
    after: ['最后一道电栅，接的是西道这根拉杆。', '把它拉到「接通」，别再动它。'],
    entrance: 'wave',
  },
  {
    id: 'gym-thunder-3',
    name: '雷阿姨',
    title: '工程师',
    ai: 'smart',
    prizeBase: 34,
    sight: { range: 7, fov: 80 },
    party: [
      { species: 94, level: 32, moves: ['thunderbolt', 'hex', 'hypnosis', 'sucker-punch'] },
      { species: 464, level: 33, moves: ['thunder-fang', 'rock-blast', 'stomp', 'scary-face'] },
    ],
    intro: ['能走到中间这条路，说明你看懂了线路图。', '最后的考验——由我来出！'],
    defeat: ['……线路图画得比我还清楚。'],
    after: ['雷霆馆主的雷丘有「避雷针」特性，电招打过去会被它吸走。', '用地面或岩石……不，用你最拿手的打法吧。'],
    entrance: 'bow',
  },
  {
    id: 'gym-thunder-leader',
    name: '雷霆',
    title: '雷鸣道馆馆主',
    ai: 'smart',
    prizeBase: 0,
    sight: { range: 0, fov: 0 },
    party: [],
    gym: 'gym-thunder',
    intro: ['我是雷霆！雷鸣镇的雷暴三百六十五天不停，避雷塔每天要挨上百次雷。', '群岛的「雷云异变」，让雷声一年比一年密。', '让我看看，你的电压够不够！'],
    defeat: ['……好！好一记响雷！'],
    after: ['雷云越来越厚了，最近北边冰川那里也不太平。', '晨光、雪原、云雀——去吧，把雷鸣群岛的徽章都拿齐。'],
    entrance: 'flex',
  },
  // —— 晨光道馆（普）——
  {
    id: 'gym-dawn-1',
    name: '阿昼',
    title: '晨跑少年',
    ai: 'smart',
    prizeBase: 30,
    sight: { range: 6, fov: 80 },
    party: [
      { species: 161, level: 31, moves: ['quick-attack', 'fury-swipes', 'follow-me', 'slam'] },
      { species: 163, level: 32, moves: ['confusion', 'reflect', 'air-slash', 'extrasensory'] },
    ],
    intro: ['日光墙在白天是实心的哦！', '想过去？先跟我比一场！'],
    defeat: ['太阳下山了……'],
    after: ['日光墙白天挡路，夜里就散了；影墙正好反过来。', '馆里的日晷都能拨动昼夜——一座拨了，整座馆都跟着变。'],
    entrance: 'wave',
  },
  {
    id: 'gym-dawn-2',
    name: '小夜',
    title: '观星少女',
    ai: 'smart',
    prizeBase: 30,
    sight: { range: 6, fov: 80 },
    party: [
      { species: 163, level: 31, moves: ['hypnosis', 'confusion', 'reflect', 'air-slash'] },
      { species: 164, level: 32, moves: ['extrasensory', 'air-slash', 'hypnosis', 'roost'] },
    ],
    intro: ['夜晚的回廊最安静了……你打扰到我看星星了！'],
    defeat: ['星星都被你吓跑了。'],
    after: ['进门的时候，馆里是白天还是黑夜，取决于外面的时间。', '迷路了就回去拨一拨日晷。'],
    entrance: 'wave',
  },
  {
    id: 'gym-dawn-3',
    name: '老钟',
    title: '钟表匠',
    ai: 'smart',
    prizeBase: 34,
    sight: { range: 7, fov: 80 },
    party: [
      { species: 20, level: 32, moves: ['hyper-fang', 'crunch', 'quick-attack', 'focus-energy'] },
      { species: 162, level: 33, moves: ['slam', 'sucker-punch', 'amnesia', 'follow-me'] },
    ],
    intro: ['时间不等人。最后一道影墙前，由我计时！'],
    defeat: ['……分秒不差，佩服。'],
    after: ['晨辉馆主的堵拦熊有「毅力」特性，中了异常状态反而更凶。', '别随便用烧伤和中毒招式。'],
    entrance: 'bow',
  },
  {
    id: 'gym-dawn-leader',
    name: '晨辉',
    title: '晨光道馆馆主',
    ai: 'smart',
    prizeBase: 0,
    sight: { range: 0, fov: 0 },
    party: [],
    gym: 'gym-dawn',
    intro: ['欢迎来到晨光道馆。我是晨辉。', '这座镇子的风车，白天迎着太阳转，夜里迎着月亮转——从不停歇。', '普通属性没有花哨的招式，只有日复一日的坚持。来吧！'],
    defeat: ['……日升日落，你都走过来了。'],
    after: ['「普之试炼」到此为止。', '去雪原镇的话，记得多穿一件——冰川下面，好像藏着什么。'],
    entrance: 'bow',
  },
  // —— 雪原道馆（冰）——
  {
    id: 'gym-snow-1',
    name: '阿凛',
    title: '滑冰选手',
    ai: 'smart',
    prizeBase: 32,
    sight: { range: 7, fov: 80 },
    party: [
      { species: 91, level: 32, moves: ['ice-shard', 'razor-shell', 'protect', 'supersonic'] },
      { species: 73, level: 32, moves: ['bubble-beam', 'hex', 'screech', 'water-pulse'] },
    ],
    intro: ['冰面上是停不下来的哦！', '在你上冰之前，先陪我热热身！'],
    defeat: ['啊——滑倒了！'],
    after: ['踏上冰面就会一直滑，直到撞上冰块才停。', '先想好路线再出发——撞上哪块冰，就停在哪里。'],
    entrance: 'wave',
  },
  {
    id: 'gym-snow-2',
    name: '冰柱',
    title: '登山家',
    ai: 'smart',
    prizeBase: 34,
    sight: { range: 7, fov: 80 },
    party: [
      { species: 195, level: 33, moves: ['avalanche', 'mud-shot', 'yawn', 'slam'] },
      { species: 342, level: 33, moves: ['avalanche', 'knock-off', 'razor-shell', 'protect'] },
    ],
    intro: ['能滑过冰场的人不多。', '霜凝大人面前，最后一关是我！'],
    defeat: ['雪崩……被你挡住了。'],
    after: ['冰属性怕火、格斗、岩石和钢。', '霜凝大人的刺甲贝会「破壳」，一旦让它破了壳，速度和攻击都会暴涨。'],
    entrance: 'flex',
  },
  {
    id: 'gym-snow-leader',
    name: '霜凝',
    title: '雪原道馆馆主',
    ai: 'smart',
    prizeBase: 0,
    sight: { range: 0, fov: 0 },
    party: [],
    gym: 'gym-snow',
    intro: ['……你滑过来了。', '我是霜凝。冰川每年只前进几厘米，却能把整座山磨平。', '冰的力量是慢的，也是不可阻挡的。让我看看你能撑多久。'],
    defeat: ['……冰，裂开了。'],
    after: ['冰川深处有一处古代遗迹，冰层里封着奇怪的蓝色光芒。', '有了「攀爬」，你就能上去看看了。'],
    entrance: 'bow',
  },
  // —— 云雀道馆（飞）——
  {
    id: 'gym-lark-1',
    name: '阿翔',
    title: '滑翔员',
    ai: 'smart',
    prizeBase: 32,
    sight: { range: 7, fov: 80 },
    party: [
      { species: 397, level: 32, moves: ['wing-attack', 'aerial-ace', 'double-team', 'quick-attack'] },
      { species: 279, level: 32, moves: ['wing-attack', 'water-pulse', 'protect', 'tailwind'] },
    ],
    intro: ['西台的风最温柔了——可我不是！'],
    defeat: ['被吹下去了……'],
    after: ['中台那座风扇，管的是西台过去的桥。', '馆主面前那座长桥，得「西风停、东风起」才托得住。'],
    entrance: 'wave',
  },
  {
    id: 'gym-lark-2',
    name: '小羽',
    title: '鸟使',
    ai: 'smart',
    prizeBase: 32,
    sight: { range: 7, fov: 80 },
    party: [
      { species: 17, level: 32, moves: ['twister', 'wing-attack', 'feather-dance', 'quick-attack'] },
      { species: 284, level: 33, moves: ['air-cutter', 'stun-spore', 'scary-face', 'water-gun'] },
    ],
    intro: ['东台的风扇是我负责的！', '想用它？赢了我再说！'],
    defeat: ['羽毛都乱了……'],
    after: ['入口那台大风扇能转向——吹向西台，还是东台。', '东台的风扇一开，通往中台的桥就托起来了。'],
    entrance: 'wave',
  },
  {
    id: 'gym-lark-3',
    name: '鹰叔',
    title: '驯鹰人',
    ai: 'smart',
    prizeBase: 36,
    sight: { range: 7, fov: 80 },
    party: [
      { species: 398, level: 33, moves: ['aerial-ace', 'take-down', 'double-team', 'whirlwind'] },
      { species: 42, level: 33, moves: ['air-cutter', 'bite', 'poison-fang', 'confuse-ray'] },
    ],
    intro: ['站在中台上，脚下就是深谷。', '怕了吗？怕了就别看下面——看着我！'],
    defeat: ['好胆量！'],
    after: ['飞行属性怕电、冰和岩石。', '云翎馆主的叉字蝠极快，先手的机会不多——准备好能扛住一击的伙伴。'],
    entrance: 'flex',
  },
  {
    id: 'gym-lark-leader',
    name: '云翎',
    title: '云雀道馆馆主',
    ai: 'smart',
    prizeBase: 0,
    sight: { range: 0, fov: 0 },
    party: [],
    gym: 'gym-lark',
    intro: ['欢迎来到云崖之巅。我是云翎。', '最近天上总有奇怪的光——像极光，又不像。鸟儿们都不敢往北飞了。', '风会告诉我答案。而现在，风想看看你！'],
    defeat: ['……风停了。'],
    after: ['天上的异象，八成和北边的琉璃群岛有关。', '你若要去，就要穿过那片终年起雾的礁海。'],
    entrance: 'bow',
  },
];
