/**
 * 萌芽群岛任务（07-22 §3.6 第一章 1–5 + §3.7 萌芽群岛支线 4 条），含 3D marker / trigger（设计 §7.2）。
 * 任务 ID、标题、奖励、flags 与 07-22 保持一致；骑乘能力以原 HM flag 表示（设计 §3.4）。
 */
import type { Quest } from '@/systems/quests';

export const SPROUT_QUESTS: Quest[] = [
  // —————————— 主线 · 第一章 异变初闻 ——————————
  {
    id: 'main-dream-prelude',
    title: '梦境序章',
    category: 'main',
    island: '萌芽群岛',
    summary: '奇怪的梦里，有个声音在呼唤你……',
    prerequisites: ['game-started'],
    completeFlag: 'dream-prelude-done',
    objectives: [{ id: 'listen', text: '听完开场梦境', completeFlag: 'dream-prelude-done' }],
  },
  {
    id: 'main-get-starter',
    title: '木兰博士的托付',
    category: 'main',
    island: '萌芽群岛',
    summary: '木兰博士在研究所等你，她准备了三只宝可梦。',
    prerequisites: ['main-dream-prelude'],
    completeFlag: 'starter-chosen',
    objectives: [
      {
        id: 'go-lab',
        text: '前往木兰博士研究所',
        completeFlag: 'lab-visited',
        marker: { island: 'sprout', position: [-20, 0, 345] },
        trigger: { type: 'reach-point', position: [-20, 0, 348], radius: 4 },
      },
      { id: 'choose', text: '在研究所选择御三家', completeFlag: 'starter-chosen', marker: { island: 'sprout', position: [-20, 0, 345] } },
    ],
    reward: { items: [{ id: 'poke-ball', qty: 5 }, { id: 'potion', qty: 2 }] },
  },
  {
    id: 'main-gym-verdant',
    title: '水之试炼',
    category: 'main',
    island: '萌芽群岛',
    summary: '穿过萌芽草原前往翠澜镇，挑战湖心道馆的馆主沧澜。',
    prerequisites: ['main-get-starter'],
    completeFlag: 'badge-verdant',
    objectives: [
      {
        id: 'reach-town',
        text: '穿过萌芽草原，前往翠澜镇',
        completeFlag: 'arrived-cuilan-town',
        marker: { island: 'sprout', zoneId: 'cuilan-town' },
        trigger: { type: 'enter-zone', zoneId: 'cuilan-town' },
      },
      {
        id: 'beat-leader',
        text: '击败翠澜道馆馆主沧澜',
        completeFlag: 'badge-verdant',
        marker: { island: 'sprout', position: [135, 0, -55] },
        trigger: { type: 'defeat', trainerId: 'gym-cuilan-leader' },
      },
    ],
    reward: { items: [{ id: 'tm-water-pulse', qty: 1 }], hm: 'hm03-surf' },
  },
  {
    id: 'main-harbor-ferry',
    title: '港湾渡船事件',
    category: 'main',
    island: '萌芽群岛',
    summary: '港湾市的渡船停航了，去问问渡船管理员发生了什么。',
    prerequisites: ['main-gym-verdant'],
    completeFlag: 'ferry-route-opened',
    objectives: [
      {
        id: 'reach-harbor',
        text: '沿湖畔前往港湾市',
        completeFlag: 'arrived-harbor-city',
        marker: { island: 'sprout', zoneId: 'harbor-city' },
        trigger: { type: 'enter-zone', zoneId: 'harbor-city' },
      },
      { id: 'talk-ferry', text: '向渡船管理员打听停航的原因', completeFlag: 'ferry-clerk-talked', marker: { island: 'sprout', position: [438, 0, 26] } },
      { id: 'ask-keeper', text: '去灯塔找灯塔守老周', completeFlag: 'lighthouse-keeper-asked', marker: { island: 'sprout', position: [418, 0, -50] } },
      { id: 'relight', text: '擦净灯室的透镜，重新点亮灯塔', completeFlag: 'lighthouse-relit', marker: { island: 'sprout', position: [418.5, 0, -63] } },
      { id: 'report-ferry', text: '回到渡船管理员那里，开通航线', completeFlag: 'ferry-route-opened', marker: { island: 'sprout', position: [438, 0, 26] } },
    ],
    reward: { items: [{ id: 'ferry-pass', qty: 1 }] },
  },
  {
    id: 'main-cross-sea-1',
    title: '首次跨海',
    category: 'main',
    island: '萌芽群岛',
    summary: '用水上骑乘从港湾市出海，横渡水路 1 抵达碧潮群岛。',
    prerequisites: ['main-harbor-ferry', 'hm03-surf'],
    completeFlag: 'cross-sea-1-done',
    objectives: [
      {
        id: 'enter-sea',
        text: '从港湾市码头出海，进入水路 1',
        completeFlag: 'sea-route-1-entered',
        marker: { island: 'sprout', zoneId: 'sea-route-1' },
        trigger: { type: 'enter-zone', zoneId: 'sea-route-1' },
      },
      // 设计 §7.4：M1 只有萌芽群岛，抵达水路 1 东端即播放结尾卡（碧潮群岛 M2 开放），目标文字调整、ID/奖励不变
      { id: 'arrive-tide', text: '横渡水路 1，驶向碧潮群岛', completeFlag: 'cross-sea-1-done', marker: { island: 'sprout', position: [506, 0, -40], radius: 20 } },
    ],
  },

  // —————————— 支线 ——————————
  {
    id: 'side-zorua-forest',
    title: '幻影之森的索罗亚',
    category: 'side',
    island: '萌芽群岛',
    summary: '有人在森林里看到伪装成人类的索罗亚。雾气会改变道路，跟着它的脚印走。',
    prerequisites: ['starter-chosen'],
    startNpc: 'cuilan-rumor-girl',
    startFlag: 'zorua-quest-start',
    completeFlag: 'zorua-quest-done',
    objectives: [
      {
        id: 'enter-forest',
        text: '进入幻影之森',
        completeFlag: 'zorua-forest-entered',
        marker: { island: 'sprout', zoneId: 'phantom-forest' },
        trigger: { type: 'enter-zone', zoneId: 'phantom-forest' },
      },
      {
        id: 'follow',
        text: '跟着脚印找到索罗亚',
        completeFlag: 'zorua-found',
        marker: { island: 'sprout', position: [-320, 0, -330], radius: 45 },
        trigger: { type: 'reach-point', position: [-320, 0, -330], radius: 8 },
      },
      { id: 'befriend', text: '赢得索罗亚的信任', completeFlag: 'zorua-quest-done' },
    ],
    reward: { pokemon: 570, pokemonLevel: 12 },
  },
  {
    id: 'side-fisherman-lost',
    title: '港湾失物招领',
    category: 'side',
    island: '萌芽群岛',
    summary: '港湾市的渔民在海上弄丢了钓具，帮他找回来。',
    prerequisites: ['badge-verdant'],
    startNpc: 'harbor-fisherman',
    startFlag: 'fisher-quest-start',
    completeFlag: 'fisher-tackle-returned',
    objectives: [
      {
        id: 'find',
        text: '在港湾外海找到漂流的钓具箱',
        completeFlag: 'fisher-tackle-found',
        marker: { island: 'sprout', position: [490, 0, 170], radius: 30 },
      },
      { id: 'return', text: '把钓具还给渔民', completeFlag: 'fisher-tackle-returned', marker: { island: 'sprout', position: [445, 0, 115] } },
    ],
    reward: { items: [{ id: 'good-rod', qty: 1 }] },
  },
  {
    id: 'side-elder-herbs',
    title: '蒲婆婆的药草',
    category: 'side',
    island: '萌芽群岛',
    summary: '萌芽镇的蒲婆婆需要岛上特有的药草，采集 3 株带回去。',
    prerequisites: ['starter-chosen'],
    startNpc: 'elder-pu',
    startFlag: 'herbs-quest-start',
    completeFlag: 'herbs-delivered',
    objectives: [
      { id: 'collect', text: '采集翠澜药草', completeFlag: 'herbs-collected', counter: { var: 'herbs-collected', target: 3 }, marker: {
          island: 'sprout',
          zoneId: 'cuilan-lakeside',
          radius: 80,
          // 3 株药草（config/story HERB_SPOTS）：罗盘 / 地图依次指向还没采的那株（离萌芽镇近的先）
          points: [
            { position: [74, 0, 96], doneFlag: 'herb-3-picked' },
            { position: [263, 0, -38], doneFlag: 'herb-1-picked' },
            { position: [198, 0, -203], doneFlag: 'herb-2-picked' },
          ],
        },
      },
      { id: 'deliver', text: '把药草交给蒲婆婆', completeFlag: 'herbs-delivered', marker: { island: 'sprout', position: [-165, 0, 395] } },
    ],
    reward: { items: [{ id: 'antidote', qty: 5 }] },
  },
  // ———————— 计划文档 §9.4 · 培育家之路（导师蒲婆婆，拿到第 1 枚徽章后） ————————
  {
    id: 'side-breeder-road-1',
    title: '培育家之路 · 起步',
    category: 'side',
    island: '萌芽群岛',
    summary: '蒲婆婆愿意收你做培育家学徒：收获树果、做一个能量方块并喂给宝可梦，再回去向她报告。',
    prerequisites: ['badge-verdant', 'farm-unlocked'],
    startNpc: 'elder-pu',
    startFlag: 'breeder-start',
    completeFlag: 'breeder-road-1',
    objectives: [
      { id: 'harvest', text: '在田里收获树果', completeFlag: 'breeder1-harvested', counter: { var: 'breeder1-harvest', target: 2, stat: 'harvest' }, marker: { island: 'sprout', position: [-122, 0, 336] } },
      { id: 'block', text: '用自家的方块机做一个能量方块', completeFlag: 'breeder1-blocked', counter: { var: 'breeder1-block', target: 1, stat: 'block' }, marker: { island: 'sprout', position: [-120, 0, 360] } },
      { id: 'feed', text: '把能量方块喂给宝可梦（背包 → 方块盒）', completeFlag: 'breeder1-fed', counter: { var: 'breeder1-feed', target: 1, stat: 'feed' } },
      { id: 'report', text: '向蒲婆婆报告', completeFlag: 'breeder-road-1', marker: { island: 'sprout', position: [-165, 0, 395] } },
    ],
    reward: { items: [{ id: 'rich-mulch', qty: 2 }, { id: 'medicinal-herb', qty: 3 }], money: 1000 },
  },
  {
    id: 'side-breeder-road-2',
    title: '培育家之路 · 培育屋',
    category: 'side',
    island: '萌芽群岛',
    summary: '成为 5 级培育家后，蒲婆婆打开了自家的培育屋：寄放一只宝可梦再领回来，并在宝可梦中心的工坊合成一件道具。',
    prerequisites: ['breeder-road-1', 'breeder-lv5'],
    startNpc: 'elder-pu',
    startFlag: 'breeder2-start',
    completeFlag: 'breeder-road-2',
    objectives: [
      { id: 'daycare', text: '在蒲婆婆的培育屋寄放并领回宝可梦', completeFlag: 'breeder2-daycare', counter: { var: 'breeder2-daycare', target: 1, stat: 'daycare' }, marker: { island: 'sprout', position: [-165, 0, 395] } },
      { id: 'craft', text: '在宝可梦中心的工坊合成道具', completeFlag: 'breeder2-crafted', counter: { var: 'breeder2-craft', target: 1, stat: 'craft' }, marker: { island: 'sprout', position: [-40, 0, -10] } },
      { id: 'report', text: '向蒲婆婆报告', completeFlag: 'breeder-road-2', marker: { island: 'sprout', position: [-165, 0, 395] } },
    ],
    reward: { items: [{ id: 'pearl', qty: 2 }, { id: 'surprise-mulch', qty: 2 }], money: 3000 },
  },
  {
    id: 'side-breeder-road-3',
    title: '培育家之路 · 翠澜培育大师',
    category: 'side',
    island: '萌芽群岛',
    summary: '蒲婆婆的最后一课：用头目之鳞和稀有树果合成一片性格薄荷，并成为 10 级培育家。',
    prerequisites: ['breeder-road-2', 'breeder-lv7'],
    startNpc: 'elder-pu',
    startFlag: 'breeder3-start',
    completeFlag: 'breeder-road-3',
    objectives: [
      { id: 'mint', text: '在工坊合成性格薄荷', completeFlag: 'breeder3-mint', counter: { var: 'breeder3-mint', target: 1, stat: 'mint' }, marker: { island: 'sprout', position: [-40, 0, -10] } },
      { id: 'master', text: '成为 10 级培育家', completeFlag: 'breeder-lv10' },
      { id: 'report', text: '向蒲婆婆报告', completeFlag: 'breeder-road-3', marker: { island: 'sprout', position: [-165, 0, 395] } },
    ],
    reward: { items: [{ id: 'gold-bottle-cap', qty: 1 }], money: 10000 },
  },
  {
    id: 'side-fishing-contest',
    title: '钓鱼大师之路',
    category: 'side',
    island: '萌芽群岛',
    summary: '港湾市钓鱼挑战赛：钓到指定的 3 种宝可梦。',
    prerequisites: ['fisher-tackle-returned'],
    startNpc: 'contest-host',
    startFlag: 'fishing-contest-start',
    completeFlag: 'fishing-contest-done',
    objectives: [
      { id: 'magikarp', text: '钓到鲤鱼王', completeFlag: 'contest-magikarp', marker: { island: 'sprout', position: [445, 0, 115] }, trigger: { type: 'catch', speciesId: 129 } },
      { id: 'tentacool', text: '钓到玛瑙水母', completeFlag: 'contest-tentacool', marker: { island: 'sprout', position: [445, 0, 115] }, trigger: { type: 'catch', speciesId: 72 } },
      { id: 'staryu', text: '在夜里钓到海星星', completeFlag: 'contest-staryu', marker: { island: 'sprout', position: [445, 0, 115] }, trigger: { type: 'catch', speciesId: 120 } },
      { id: 'report', text: '向主持人报告', completeFlag: 'fishing-contest-done', marker: { island: 'sprout', position: [440, 0, 100] } },
    ],
    reward: { items: [{ id: 'super-rod', qty: 1 }], money: 2000 },
  },
  // ———————— 剧情线 · 玩法覆盖（2026-10-02）：捕获 / 训练家对战 / 回复与购物 / 冲浪与钓鱼 / 夜间探索 / 进化 ————————
  {
    id: 'side-dex-first-page',
    title: '图鉴的第一页',
    category: 'side',
    island: '萌芽群岛',
    summary: '研究员小周想看看新训练家的图鉴：去草丛里捕捉 3 只宝可梦，再回研究所给他看。',
    prerequisites: ['starter-chosen'],
    startNpc: 'lab-aide-1',
    startFlag: 'dexpage-start',
    completeFlag: 'dexpage-done',
    objectives: [
      { id: 'catch', text: '捕捉野生宝可梦', completeFlag: 'dexpage-caught', counter: { var: 'dexpage-caught', target: 3, stat: 'catch' }, marker: { island: 'sprout', zoneId: 'sprout-meadow', radius: 70 } },
      { id: 'report', text: '回研究所向小周展示图鉴', completeFlag: 'dexpage-done', marker: { island: 'sprout', position: [-20, 0, 345] } },
    ],
    reward: { items: [{ id: 'poke-ball', qty: 5 }, { id: 'potion', qty: 3 }] },
  },
  {
    id: 'side-trainer-road',
    title: '草原训练家之路',
    category: 'side',
    island: '萌芽群岛',
    summary: '短裤小子阿健说：真正的训练家要在路上接受挑战。战胜 3 位训练家后回来找他。',
    prerequisites: ['starter-chosen'],
    startNpc: 'route1-youngster',
    startFlag: 'trainerroad-start',
    completeFlag: 'trainerroad-done',
    objectives: [
      { id: 'battles', text: '战胜训练家', completeFlag: 'trainerroad-won', counter: { var: 'trainerroad-wins', target: 3, stat: 'trainer-win' }, marker: { island: 'sprout', zoneId: 'sprout-meadow', radius: 90 } },
      { id: 'report', text: '向阿健报告', completeFlag: 'trainerroad-done', marker: { island: 'sprout', position: [-56, 0, 250] } },
    ],
    reward: { items: [{ id: 'great-ball', qty: 3 }], money: 1500 },
  },
  {
    id: 'side-travel-prep',
    title: '旅行准备',
    category: 'side',
    island: '萌芽群岛',
    summary: '宝可梦中心的旅行者美穗教你出远门前的准备：让宝可梦恢复精神，再去商店补给。',
    prerequisites: ['arrived-cuilan-town'],
    startNpc: 'center-visitor',
    startFlag: 'travelprep-start',
    completeFlag: 'travelprep-done',
    objectives: [
      { id: 'heal', text: '在宝可梦中心回复宝可梦', completeFlag: 'travelprep-healed', counter: { var: 'travelprep-heals', target: 1, stat: 'heal' }, marker: { island: 'sprout', position: [-40, 0, -10] } },
      { id: 'buy', text: '在友好商店买一件道具', completeFlag: 'travelprep-bought', counter: { var: 'travelprep-buys', target: 1, stat: 'buy' }, marker: { island: 'sprout', position: [-55, 0, -70] } },
      { id: 'report', text: '回宝可梦中心告诉美穗', completeFlag: 'travelprep-done', marker: { island: 'sprout', position: [-40, 0, -10] } },
    ],
    reward: { items: [{ id: 'super-potion', qty: 2 }, { id: 'antidote', qty: 2 }] },
  },
  {
    id: 'side-lake-light',
    title: '湖底的光',
    category: 'side',
    island: '萌芽群岛',
    summary: '钓鱼老伯说，翠澜湖上常闪起微光。冲浪到光点看看，再在湖上钓一次鱼。',
    prerequisites: ['hm03-surf'],
    startNpc: 'cuilan-old-man',
    startFlag: 'lakelight-start',
    completeFlag: 'lakelight-done',
    objectives: [
      { id: 'surf', text: '骑上宝可梦冲浪下水', completeFlag: 'lakelight-surfed', counter: { var: 'lakelight-surf', target: 1, stat: 'surf' }, marker: { island: 'sprout', position: [-30, 0, -45] } },
      { id: 'center', text: '冲浪到翠澜湖东南的光点', completeFlag: 'lakelight-center', marker: { island: 'sprout', position: [205, 0, -110] }, trigger: { type: 'reach-point', position: [205, 0, -110], radius: 14 } },
      { id: 'fish', text: '在湖上钓起一只宝可梦', completeFlag: 'lakelight-fished', counter: { var: 'lakelight-fish', target: 1, stat: 'fish' }, marker: { island: 'sprout', position: [205, 0, -110], radius: 30 } },
      { id: 'report', text: '向钓鱼老伯说说湖底的光', completeFlag: 'lakelight-done', marker: { island: 'sprout', position: [-62, 0, -36] } },
    ],
    reward: { items: [{ id: 'revive', qty: 1 }], money: 2000 },
  },
  {
    id: 'side-forest-whisper',
    title: '森林的低语',
    category: 'side',
    island: '萌芽群岛',
    summary: '登山客大石在夜里听到幻影之森传来奇怪的声音。等到夜晚，沿着林道上的发光足迹走进森林。',
    prerequisites: ['starter-chosen'],
    startNpc: 'route1-hiker',
    startFlag: 'whisper-start',
    completeFlag: 'whisper-done',
    objectives: [
      { id: 'print1', text: '夜里找到林道入口的足迹', completeFlag: 'whisper-print-1', marker: { island: 'sprout', position: [-150, 0, -110] }, trigger: { type: 'reach-point', position: [-150, 0, -110], radius: 8, night: true } },
      { id: 'print2', text: '夜里沿足迹深入森林', completeFlag: 'whisper-print-2', marker: { island: 'sprout', position: [-172, 0, -155] }, trigger: { type: 'reach-point', position: [-172, 0, -155], radius: 8, night: true } },
      { id: 'print3', text: '夜里找到足迹的尽头', completeFlag: 'whisper-print-3', marker: { island: 'sprout', position: [-190, 0, -200] }, trigger: { type: 'reach-point', position: [-190, 0, -200], radius: 8, night: true } },
      { id: 'calm', text: '打倒在林中徘徊的野生宝可梦', completeFlag: 'whisper-calm', counter: { var: 'whisper-wins', target: 2, stat: 'wild-win' }, marker: { island: 'sprout', zoneId: 'phantom-forest', radius: 60 } },
      { id: 'report', text: '回去告诉大石', completeFlag: 'whisper-done', marker: { island: 'sprout', position: [-24, 0, 102] } },
    ],
    reward: { items: [{ id: 'great-ball', qty: 2 }, { id: 'super-potion', qty: 1 }] },
  },
  {
    id: 'side-partner-growth',
    title: '伙伴的成长',
    category: 'side',
    island: '萌芽群岛',
    summary: '研究员阿芳在研究宝可梦进化：多和野生宝可梦战斗积累经验，让一只宝可梦进化后回来报告。',
    prerequisites: ['badge-verdant'],
    startNpc: 'lab-aide-2',
    startFlag: 'growth-start',
    completeFlag: 'growth-done',
    objectives: [
      { id: 'train', text: '打倒野生宝可梦积累经验', completeFlag: 'growth-trained', counter: { var: 'growth-wins', target: 5, stat: 'wild-win' }, marker: { island: 'sprout', zoneId: 'cuilan-lakeside', radius: 90 } },
      { id: 'evolve', text: '让一只宝可梦进化', completeFlag: 'growth-evolved', counter: { var: 'growth-evolve', target: 1, stat: 'evolve' } },
      { id: 'report', text: '回研究所向阿芳报告', completeFlag: 'growth-done', marker: { island: 'sprout', position: [-20, 0, 345] } },
    ],
    reward: { items: [{ id: 'super-potion', qty: 3 }, { id: 'revive', qty: 1 }], money: 3000 },
  },
];
