/**
 * M2-16/17 · 碧潮群岛任务（07-22 §3.6 第二章 6–13 + §3.7 碧潮群岛支线 6 条），含 3D marker / trigger。
 * 任务 ID、标题、奖励与 07-22 一致；徽章名暂统一为「翠澜徽章」（命名待定）；骑乘 / 场地能力以 flag 表示：
 *   field-cut（居合劈，碧潮道馆）· field-flash（闪光，碧焰道馆）· hm06-strength（怪力，矿洞救援）· hm05-rock-smash（碎岩，原初守护者）。
 * 三座道馆挑战顺序自由（动态等级按本岛徽章数取档）。
 */
import type { Quest } from '@/systems/quests';

const ISLAND = '碧潮群岛';

export const TIDE_QUESTS: Quest[] = [
  // —————————— 主线 · 第二章 异变痕迹 ——————————
  {
    id: 'main-gym-azure',
    title: '古树低语',
    category: 'main',
    island: ISLAND,
    summary: '碧潮镇的巨树下有一座道馆。挑战草属性馆主叶岚，得到古森的认可。',
    prerequisites: ['main-cross-sea-1'],
    completeFlag: 'badge-azure',
    objectives: [
      {
        id: 'reach-town',
        text: '前往碧潮镇',
        completeFlag: 'arrived-tide-town',
        marker: { island: 'tide', zoneId: 'tide-town' },
        trigger: { type: 'enter-zone', zoneId: 'tide-town' },
      },
      {
        id: 'beat-leader',
        text: '击败碧潮道馆馆主叶岚',
        completeFlag: 'badge-azure',
        marker: { island: 'tide', position: [-470, 0, -52] },
        trigger: { type: 'defeat', trainerId: 'gym-azure-leader' },
      },
    ],
    reward: { items: [{ id: 'tm-magical-leaf', qty: 1 }], hm: 'field-cut' },
  },
  {
    id: 'main-mine-anomaly',
    title: '矿洞异变',
    category: 'main',
    island: ISLAND,
    summary: '矿石镇矿洞深处的晶石变成了紫色。工头老铁想请人下去看看。',
    prerequisites: ['main-cross-sea-1'],
    completeFlag: 'mine-anomaly-reported',
    objectives: [
      { id: 'talk-foreman', text: '在矿工工头之家找工头老铁', completeFlag: 'mine-anomaly-start', marker: { island: 'tide', position: [150, 0, 240] } },
      { id: 'investigate', text: '调查矿洞深层矿脉的异变痕迹', completeFlag: 'mine-anomaly-found', marker: { island: 'tide', position: [104, 0, -104] } },
      { id: 'report', text: '回矿石镇向老铁报告', completeFlag: 'mine-anomaly-reported', marker: { island: 'tide', position: [150, 0, 240] } },
    ],
    reward: { items: [{ id: 'anomaly-shard-red', qty: 1 }] },
  },
  {
    id: 'main-gym-ore',
    title: '岩之试炼',
    category: 'main',
    island: ISLAND,
    summary: '矿石镇的工头岩磊也是道馆馆主。在采石场道馆挑战岩石属性的他。',
    prerequisites: ['main-cross-sea-1'],
    completeFlag: 'badge-ore',
    objectives: [
      {
        id: 'reach-town',
        text: '沿古树林道前往矿石镇',
        completeFlag: 'arrived-ore-town',
        marker: { island: 'tide', zoneId: 'ore-town' },
        trigger: { type: 'enter-zone', zoneId: 'ore-town' },
      },
      {
        id: 'beat-leader',
        text: '击败矿石道馆馆主岩磊',
        completeFlag: 'badge-ore',
        marker: { island: 'tide', position: [120, 0, 200] },
        trigger: { type: 'defeat', trainerId: 'gym-ore-leader' },
      },
    ],
    reward: { items: [{ id: 'tm-rock-tomb', qty: 1 }] },
  },
  {
    id: 'main-volcano-heat',
    title: '地热异常',
    category: 'main',
    island: ISLAND,
    summary: '火山镇的地热一个月来不断升高，火山口涌出灼人的热浪。去地热观测站问问情况。',
    prerequisites: ['main-cross-sea-1'],
    completeFlag: 'volcano-heat-cleared',
    objectives: [
      { id: 'talk-chief', text: '在火山镇地热观测站找站长老秦', completeFlag: 'volcano-heat-start', marker: { island: 'tide', position: [626, 0, 98] } },
      { id: 'core', text: '深入火山洞窟，调查地热核心', completeFlag: 'volcano-heat-source-found', marker: { island: 'tide', position: [724, 0, -140] } },
      { id: 'report', text: '回观测站向老秦报告', completeFlag: 'volcano-heat-cleared', marker: { island: 'tide', position: [626, 0, 98] } },
    ],
    reward: { items: [{ id: 'anomaly-shard-orange', qty: 1 }] },
  },
  {
    id: 'main-gym-flame',
    title: '火之试炼',
    category: 'main',
    island: ISLAND,
    summary: '火山镇的碧焰道馆建在熔岩之上。挑战火属性馆主炎棘。',
    prerequisites: ['main-cross-sea-1'],
    completeFlag: 'badge-flame',
    objectives: [
      {
        id: 'reach-town',
        text: '穿过余烬小径前往火山镇',
        completeFlag: 'arrived-flame-town',
        marker: { island: 'tide', zoneId: 'flame-town' },
        trigger: { type: 'enter-zone', zoneId: 'flame-town' },
      },
      {
        id: 'beat-leader',
        text: '击败碧焰道馆馆主炎棘',
        completeFlag: 'badge-flame',
        marker: { island: 'tide', position: [600, 0, 34] },
        trigger: { type: 'defeat', trainerId: 'gym-flame-leader' },
      },
    ],
    reward: { items: [{ id: 'tm-incinerate', qty: 1 }], hm: 'field-flash' },
  },
  {
    id: 'main-ruins-seal',
    title: '封印真相',
    category: 'main',
    island: ISLAND,
    summary: '中央高原的异变遗迹被紫色结界封住。集齐碧潮群岛的三枚徽章，结界也许会回应。',
    prerequisites: ['main-gym-azure', 'main-gym-ore', 'main-gym-flame'],
    completeFlag: 'ruins-entered',
    objectives: [
      {
        id: 'reach-gate',
        text: '带着三枚徽章前往中央高原的异变遗迹',
        completeFlag: 'ruins-seal-open',
        marker: { island: 'tide', position: [44, 0, -400] },
      },
      { id: 'enter', text: '进入异变遗迹', completeFlag: 'ruins-entered', marker: { island: 'tide', position: [44, 0, -428] } },
    ],
  },
  {
    id: 'main-ruins-boss',
    title: '原初守护者',
    category: 'main',
    island: ISLAND,
    summary: '遗迹深处的圣所里，沉睡着古代人留下的守护者。',
    prerequisites: ['main-ruins-seal'],
    completeFlag: 'ruins-guardian-defeated',
    objectives: [
      { id: 'sanctum', text: '穿过壁画回廊，前往守护者圣所', completeFlag: 'ruins-sanctum-reached', marker: { island: 'tide', position: [44, 0, -428] } },
      { id: 'defeat', text: '击败原初守护者', completeFlag: 'ruins-guardian-defeated', marker: { island: 'tide', position: [44, 0, -428] } },
    ],
    reward: { items: [{ id: 'anomaly-shard-purple', qty: 1 }], hm: 'hm05-rock-smash' },
  },
  {
    id: 'main-hot-spring-info',
    title: '温泉情报',
    category: 'main',
    island: ISLAND,
    summary: '听说温泉乡旅馆里的汤婆婆，知道群岛古代文明的往事。',
    prerequisites: ['main-ruins-boss'],
    completeFlag: 'hot-spring-info-heard',
    objectives: [
      {
        id: 'reach-village',
        text: '前往东南的温泉乡',
        completeFlag: 'arrived-spring-village',
        marker: { island: 'tide', zoneId: 'spring-village' },
        trigger: { type: 'enter-zone', zoneId: 'spring-village' },
      },
      { id: 'listen', text: '在温泉旅馆「汤之庭」听汤婆婆讲古', completeFlag: 'hot-spring-info-heard', marker: { island: 'tide', position: [410, 0, 600] } },
    ],
  },

  // —————————— 支线 ——————————
  {
    id: 'side-forest-child',
    title: '碧潮古森迷路童',
    category: 'side',
    island: ISLAND,
    summary: '碧潮镇的小芽跑进古森找发光蘑菇，迷路了。把他找回来。',
    prerequisites: ['main-cross-sea-1'],
    startNpc: 'forest-child-mom',
    startFlag: 'forest-child-start',
    completeFlag: 'forest-child-done',
    objectives: [
      { id: 'find', text: '在碧潮古森北边的池塘附近找到小芽', completeFlag: 'forest-child-found', marker: { island: 'tide', position: [-310, 0, -310], radius: 40 } },
      { id: 'return', text: '回碧潮镇告诉小芽妈妈', completeFlag: 'forest-child-done', marker: { island: 'tide', position: [-452, 0, 40] } },
    ],
    reward: { items: [{ id: 'miracle-seed', qty: 1 }] },
  },
  {
    id: 'side-mine-rescue',
    title: '矿洞救援',
    category: 'side',
    island: ISLAND,
    summary: '工头家的侄子石根被困在矿洞深处，塌方处还有一条大岩蛇守着。',
    prerequisites: ['main-cross-sea-1'],
    startNpc: 'foreman-wife',
    startFlag: 'mine-rescue-start',
    completeFlag: 'mine-rescue-done',
    objectives: [
      { id: 'rescue', text: '在矿洞深层矿脉东侧救出石根', completeFlag: 'mine-miner-rescued', marker: { island: 'tide', position: [104, 0, -104] } },
      { id: 'report', text: '回工头之家告诉铁嫂', completeFlag: 'mine-rescue-done', marker: { island: 'tide', position: [150, 0, 240] } },
    ],
    reward: { hm: 'hm06-strength', items: [{ id: 'super-potion', qty: 3 }] },
  },
  {
    id: 'side-volcano-egg',
    title: '火山口的蛋',
    category: 'side',
    island: ISLAND,
    summary: '火山洞窟里捡到一枚温热的蛋。温泉乡的培育屋也许能孵化它。',
    prerequisites: ['main-cross-sea-1'],
    startFlag: 'volcano-egg-found',
    completeFlag: 'volcano-egg-hatched',
    objectives: [{ id: 'hatch', text: '把蛋带到温泉乡的培育屋', completeFlag: 'volcano-egg-hatched', marker: { island: 'tide', position: [340, 0, 548] } }],
    reward: { pokemon: 636, pokemonLevel: 5 },
  },
  {
    id: 'side-hot-spring-source',
    title: '温泉源头疏通',
    category: 'side',
    island: ISLAND,
    summary: '温泉乡的温泉不热了——上游泉眼被落石堵住。需要「碎岩」撞开它。',
    prerequisites: ['main-cross-sea-1'],
    startNpc: 'inn-owner',
    startFlag: 'spring-source-start',
    completeFlag: 'spring-source-done',
    objectives: [
      { id: 'smash', text: '用「碎岩」撞开温泉溪上游的落石', completeFlag: 'cleared:spring-source-rock', marker: { island: 'tide', position: [588, 0, 312] } },
      { id: 'report', text: '回汤之庭告诉汤老板', completeFlag: 'spring-source-done', marker: { island: 'tide', position: [410, 0, 600] } },
    ],
    reward: { items: [{ id: 'fire-stone', qty: 1 }] },
  },
  {
    id: 'side-ancient-tablet',
    title: '古代石板解读',
    category: 'side',
    island: ISLAND,
    summary: '矿洞深处的石室里发现了刻着群岛历史的石板。带给木兰博士看看。',
    prerequisites: ['main-cross-sea-1'],
    startFlag: 'ancient-tablet-found',
    completeFlag: 'ancient-tablet-delivered',
    objectives: [{ id: 'deliver', text: '把古代石板交给萌芽镇的木兰博士', completeFlag: 'ancient-tablet-delivered', marker: { island: 'sprout', position: [-20, 0, 345] } }],
    reward: { money: 5000, items: [{ id: 'ultra-ball', qty: 5 }] },
  },
  {
    id: 'side-anomaly-survivor',
    title: '异变幸存者',
    category: 'side',
    island: ISLAND,
    summary: '五十年前群岛也发生过异变。寻访当年的三位幸存者，听他们讲述往事。',
    prerequisites: ['main-cross-sea-1'],
    startNpc: 'tide-elder',
    startFlag: 'survivor-1-heard',
    completeFlag: 'anomaly-survivor-done',
    objectives: [
      { id: 'elder', text: '听碧潮镇树语长老讲述', completeFlag: 'survivor-1-heard', marker: { island: 'tide', position: [-540, 0, 78] } },
      { id: 'miner', text: '听矿石镇的石根老爹讲述', completeFlag: 'survivor-2-heard', marker: { island: 'tide', position: [70, 0, 214] } },
      { id: 'grandma', text: '听温泉乡汤之庭的汤婆婆讲述', completeFlag: 'anomaly-survivor-done', marker: { island: 'tide', position: [410, 0, 600] } },
    ],
    reward: { items: [{ id: 'anomaly-shard-memory', qty: 1 }] },
  },
];
