/**
 * M3-11 ~ M3-14 · 琉璃群岛城镇 NPC。道馆馆主与道馆训练家在 M3-16 加入；人物造型为程序化占位（M2-19 决议）。
 * 幻影镇的摊主日程与 towns/glaze.ts 的 MIRAGE_HOURS 一致：白日市集 7–18 时、月夜集市 19–3 时。
 */
import type { NpcDef } from '@/systems/npcs';
import { MIRAGE_HOURS } from '@/config/islands/towns/glaze';

const PI = Math.PI;
const [B0, B1] = MIRAGE_HOURS.bazaar;
const [N0, N1] = MIRAGE_HOURS.nightMarket;

export const GLAZE_NPCS: NpcDef[] = [
  // ———————————————————————————— 幻影镇 ————————————————————————————
  {
    id: 'mirage-guide',
    name: '道馆向导',
    title: '幻影道馆',
    appearance: { look: 'guide', palette: { cap: '#7a4a9a', jacket: '#7a4a9a' } },
    schedule: [{ from: 0, to: 24, at: { island: 'glaze', position: [-388, 404], yaw: 0 } }],
    dialog: ['这里是幻影道馆，馆主幻月用的是超能力属性的宝可梦。', '馆里到处是传送镜——走错一步就会被送回门口。', '恶属性和虫属性的招式对超能系很有效，记住了！'],
  },
  {
    id: 'mirage-scholar',
    name: '蜃学者沙洛',
    title: '海市蜃楼研究者',
    appearance: { look: 'researcher', palette: { jacket: '#efe2c8', hair: '#5a4a3a' }, style: { glasses: true } },
    schedule: [
      { from: 6, to: 18, at: { island: 'glaze', position: [-252, 466], yaw: PI / 2 }, activity: { kind: 'wander', radius: 2 } },
      { from: 18, to: 6, at: { island: 'glaze', position: [-470, 498], yaw: -PI / 2 }, activity: { kind: 'wander', radius: 2 } },
    ],
    dialog: ['幻影镇的房子……不是每一栋都一直在。', '上午十点到下午四点，东边沙丘上会浮现一座宫殿和两座高塔。走过去的话，你会直接穿过去。', '而到了晚上八点，镇西口外会出现月影塔——那座塔是摸得着的！天一亮就消失得无影无踪。', '我研究了二十年，还是不知道哪边才是「真的」。'],
  },
  {
    id: 'mirage-bazaar-fruit',
    name: '椰枣大叔',
    title: '白日市集',
    appearance: { look: 'vendor', palette: { jacket: '#d86a4a' } },
    schedule: [{ from: B0, to: B1, at: { island: 'glaze', position: [-402, 428], yaw: PI / 2 } }],
    dialog: ['新鲜的椰枣、仙人掌果！', '天一黑我们就收摊——这片广场到了晚上可是空荡荡的，连摊子都看不见。'],
  },
  {
    id: 'mirage-bazaar-potter',
    name: '陶罐婆婆',
    title: '白日市集',
    appearance: { look: 'elder', palette: { jacket: '#3f8aa8' } },
    schedule: [{ from: B0, to: B1, at: { island: 'glaze', position: [-358, 428], yaw: -PI / 2 } }],
    dialog: ['这些陶罐是用蜃景沙丘的沙子烧的。', '对着罐口说话，过一会儿会听到回声……有时候回声说的话跟你说的不一样。'],
  },
  {
    id: 'mirage-night-vendor',
    name: '月灯姑娘',
    title: '月夜集市',
    appearance: { look: 'kimono-f', palette: { jacket: '#4b4a78', hair: '#2a2a3a' } },
    schedule: [{ from: N0, to: N1, at: { island: 'glaze', position: [-397, 500], yaw: PI / 2 } }],
    dialog: ['欢迎来到月夜集市～', '这个集市只在月亮出来的时候开张，天亮之前就会散。', '白天来找我？那你只会看到一条空荡荡的码头路哦。'],
  },
  {
    id: 'mirage-night-charm',
    name: '护符商人',
    title: '月夜集市',
    appearance: { look: 'villager-m', palette: { jacket: '#5b4a78' } },
    schedule: [{ from: N0, to: N1, at: { island: 'glaze', position: [-363, 512], yaw: -PI / 2 } }],
    dialog: ['看看这些护符吧，都是在月影塔下开过光的。', '月影塔？晚上八点以后去镇西口外看看就知道了。'],
  },
  {
    id: 'mirage-villager-1',
    name: '纱丽阿姨',
    title: '幻影镇居民',
    appearance: { look: 'villager-f', palette: { jacket: '#3f7a8a' }, style: { apron: true } },
    schedule: [{ from: 7, to: 20, at: { island: 'glaze', position: [-440, 452], yaw: 0 }, activity: { kind: 'wander', radius: 3 } }],
    dialog: ['我们镇上的房子都刷成白色，屋顶是青色的玻璃穹顶。', '太阳最毒的时候，整座镇子都在热浪里晃——分不清哪栋是真的。'],
  },
  {
    id: 'mirage-kid',
    name: '小蜃',
    title: '幻影镇的孩子',
    appearance: { look: 'child-f', palette: { jacket: '#7fd6d8' } },
    schedule: [{ from: 9, to: 18, at: { island: 'glaze', position: [-374, 474], yaw: PI }, activity: { kind: 'wander', radius: 4 } }],
    dialog: ['我昨天跑进蜃楼宫里面了！', '……可是里面什么都没有，只有沙子。妈妈说那是「海市蜃楼」。'],
  },
  {
    id: 'mirage-fisher',
    name: '老船夫',
    title: '幻影镇码头',
    appearance: { look: 'sailor', palette: { jacket: '#3f6a9a' } },
    schedule: [{ from: 5, to: 21, at: { island: 'glaze', position: [-380, 576], yaw: 0 } }],
    dialog: ['你是从雷鸣那边穿过礁石迷宫过来的？了不起！', '迷宫里认准红绿浮标，缺口就在两只浮标中间。', '回去的话，一路往南冲浪就行。'],
  },
  // ——— 先知之家 ———
  {
    id: 'mirage-seer',
    name: '先知娜芙',
    title: '幻影镇的先知',
    appearance: { look: 'kimono-f', palette: { jacket: '#7a4a9a', hair: '#e8e2ff' } },
    dialogByQuest: [
      { questId: 'side-mirage-prophecy', when: 'completed', dialog: ['已去之地、将至之门、群岛之外……', '你走的路，正是预言里写的路。'] },
      { questId: 'side-mirage-prophecy', when: 'active', requires: ['prophecy-1', 'prophecy-2', 'prophecy-3'], setFlags: ['prophecy-done'], dialog: ['……白昼之宫映出已去之地，月下之塔指向将至之门，海底之门通往群岛之外。', '七块碎片会在群岛之外重聚。孩子，那就是你要去的地方。', '这支「弯曲的汤匙」和「精神强念」的学习器，是先知一脉的信物。带上它们吧。'] },
      { questId: 'side-mirage-prophecy', when: 'active', dialog: ['蜃楼宫、月影塔、神殿石碑。预言只对亲临的人开口。'] },
      { questId: 'side-mirage-prophecy', when: 'available', setFlags: ['prophecy-start'], dialog: ['水晶球里映出三段预言。可惜，它们只肯对亲眼看见的人开口。', '白昼之宫——蜃楼宫观景处。月下之塔——月影塔遗址。海底之门——琉璃镇东边的神殿石碑。', '去那三个地方，听听它们说什么，再回来告诉我。'] },
    ],
    dialog: ['……我等你很久了，从雷鸣来的训练家。', '水晶球里映出三段预言：「白昼之宫」「月下之塔」「海底之门」。', '前两段就在这座镇子里。最后一段……要等琉璃之海告诉你。'],
  },
  {
    id: 'mirage-seer-apprentice',
    name: '学徒小望',
    title: '先知的学徒',
    appearance: { look: 'youngster', palette: { jacket: '#3f7a8a' } },
    dialog: ['师父说预言石柱上的符文会在夜里发光。', '我抄了好几个晚上，还是看不懂……'],
  },
  // ———————————————————————————— 幽冥镇 ————————————————————————————
  {
    id: 'ghost-guide',
    name: '道馆向导',
    title: '幽冥道馆',
    appearance: { look: 'guide', palette: { cap: '#a88af0', jacket: '#4a3e5a' } },
    schedule: [{ from: 0, to: 24, at: { island: 'glaze', position: [-436, -192], yaw: 0 } }],
    dialog: ['这里是幽冥道馆，馆主幽魄用的是幽灵属性的宝可梦。', '馆里一片漆黑，只有灵火照亮的路是安全的。', '幽灵系招式对幽灵系效果拔群，恶属性也很管用。一般和格斗招式可是打不中它们的！'],
  },
  {
    id: 'ghost-lamplighter',
    name: '点灯人阿烛',
    title: '幽冥镇点灯人',
    appearance: { look: 'villager-m', palette: { jacket: '#3a3444', cap: '#2e2a3a' } },
    schedule: [
      { from: 17, to: 7, at: { island: 'glaze', position: [-458, -172], yaw: 0 }, activity: { kind: 'wander', radius: 6 } },
      { from: 7, to: 17, at: { island: 'glaze', position: [-512, -176], yaw: PI } },
    ],
    dialog: ['镇上的灯笼点的都是灵火——不是我点的，是它们自己亮的。', '我只负责数一数，看有没有哪盏灯走丢了。', '雾太浓的时候，有些灯会自己飘到墓园那边去……'],
  },
  {
    id: 'ghost-kid',
    name: '胆小的小陌',
    title: '幽冥镇的孩子',
    appearance: { look: 'child-m', palette: { jacket: '#5a8aa8' } },
    schedule: [{ from: 7, to: 19, at: { island: 'glaze', position: [-470, -150], yaw: PI / 2 }, activity: { kind: 'wander', radius: 3 } }],
    dialog: ['我、我才不怕！', '……可是半夜十二点到三点，墓园里会多出好多鬼火，我奶奶说那是在开会。', '你要是敢去看，回来告诉我它们开会说了什么！'],
  },
  {
    id: 'ghost-villager',
    name: '提灯婆婆',
    title: '幽冥镇居民',
    appearance: { look: 'elder', palette: { jacket: '#4a3e5a' } },
    schedule: [{ from: 6, to: 21, at: { island: 'glaze', position: [-520, -165], yaw: 0 }, activity: { kind: 'wander', radius: 3 } }],
    dialog: ['这镇子的雾从来没散过，白天也一样。', '屋顶上尖尖的窗户是为了让灵魂找到回家的路。', '钟楼的钟每到午夜会自己响——没人敢去拉那根绳子。'],
  },
  {
    id: 'ghost-stilt-fisher',
    name: '沼泽钓客',
    title: '高脚屋居民',
    appearance: { look: 'fisher', palette: { jacket: '#5a6a4a' } },
    schedule: [{ from: 5, to: 22, at: { island: 'glaze', position: [-572, -112], yaw: -PI / 2 } }],
    dialog: ['沼泽里钓不到什么大鱼，倒是常钓上来会笑的泥巴。', '高脚屋是为了雨季涨水盖的。住习惯了，比镇上的石头房子暖和。'],
  },
  // ——— 守墓人之家 ———
  {
    id: 'ghost-gravekeeper',
    name: '守墓人老墨',
    title: '幽冥墓园守墓人',
    appearance: { look: 'elder', palette: { jacket: '#2e2a3a', hair: '#d8d4dc' } },
    dialogByQuest: [
      { questId: 'side-spirit-seance', when: 'completed', dialog: ['没名字的墓碑上，名字都回来了。', '谢谢你替我送它们一程。'] },
      { questId: 'side-spirit-seance', when: 'active', requires: ['spirit-1-calmed', 'spirit-2-calmed', 'spirit-3-calmed'], setFlags: ['seance-done'], dialog: ['三个都安息了？……我听见钟声了。', '这张招式学习器是灵堂留下的「怨恨」——专门对付那些不讲理的对手。收下吧。'] },
      { questId: 'side-spirit-seance', when: 'active', dialog: ['墓园、沼泽古墓、钟楼下。鬼火亮着的地方，就是它们在等。'] },
      { questId: 'side-spirit-seance', when: 'available', setFlags: ['seance-start'], dialog: ['你看得见它们？……那就好办了。', '这几个月，墓园里多了没写名字的墓碑。那是被异变惊醒、忘了自己是谁的亡魂。', '墓园、沼泽古墓、钟楼下——各有一个在徘徊。用你的宝可梦陪它们打一场，它们就会想起来。', '去吧。它们只是迷路了。'] },
    ],
    dialog: ['墓园里躺着的，有人，也有宝可梦。', '每块墓碑我都记得。最近却多了几块没写名字的……', '午夜零点到三点别去墓园。不是危险——只是那段时间，它们不喜欢被打扰。'],
  },
  // ——— 灵堂 ———
  {
    id: 'ghost-priestess',
    name: '守灵巫女澄',
    title: '灵堂巫女',
    appearance: { look: 'kimono-f', palette: { jacket: '#e8e2f0', hair: '#2a2a3a' } },
    dialogByQuest: [
      {
        questId: 'main-ghost-event',
        when: 'available',
        setFlags: ['ghost-event-start'],
        dialog: [
          '……你身上带着和那道光一样的东西。',
          '这一个月，幽冥镇每晚都有亡魂在哭。灯一盏一盏地灭，墓园里多了没写名字的墓碑。',
          '低吟声是从镇北的暗影洞窟传出来的。洞底有一座古代海民的祭坛。',
          '请你去看看。洞里很深很黑，带上会「闪光」「怪力」「碎岩」的伙伴。',
        ],
      },
      { questId: 'main-ghost-event', when: 'active', dialog: ['暗影洞窟在镇子北边。低吟声……今晚又更响了。'] },
      { questId: 'main-ghost-event', when: 'completed', dialog: ['昨夜，镇上的灯一盏都没灭。', '谢谢你让它们安息。灵魂终于可以回到琉璃之海了。'] },
    ],
    dialog: ['欢迎来到灵堂。请放轻脚步。', '这里供奉着翠澜古代海民的遗骨。他们相信，灵魂最终都会回到琉璃之海。', '幽魄馆主每个月都会来这里祈祷。他说，幽灵宝可梦也有想念的人。'],
  },
  {
    id: 'ghost-mourner',
    name: '悼念者',
    title: '灵堂访客',
    appearance: { look: 'villager-f', palette: { jacket: '#3a3444' } },
    dialogByQuest: [
      { questId: 'main-ghost-event', when: 'completed', dialog: ['昨晚窗外那对红眼睛又来了。', '这次它没有笑……它冲我挥了挥手，然后就慢慢散开了。', '……谢谢你。'] },
    ],
    dialog: ['……我的耿鬼陪了我二十年。', '有时候夜里，我还能看见窗外有一对红眼睛在笑。'],
  },
  // ———————————————————————————— 琉璃镇 ————————————————————————————
  {
    id: 'glaze-guide',
    name: '道馆向导',
    title: '琉璃道馆',
    appearance: { look: 'guide', palette: { cap: '#2a6aa8', jacket: '#5fc8e0' } },
    schedule: [{ from: 0, to: 24, at: { island: 'glaze', position: [480, 122], yaw: 0 } }],
    dialog: ['这里是琉璃道馆，馆主琉璃用的是水属性的宝可梦。', '馆里的水位会升降——踩对开关，水路才会连起来。', '草属性和电属性的招式对水系很有效！'],
  },
  {
    id: 'glaze-temple-scholar',
    name: '海民学者澜',
    title: '海底神殿研究者',
    appearance: { look: 'researcher', palette: { jacket: '#e8f0f4', hair: '#3a4a5a' }, style: { glasses: true } },
    schedule: [
      { from: 7, to: 19, at: { island: 'glaze', position: [601, 186], yaw: PI / 2 }, activity: { kind: 'wander', radius: 2 } },
      { from: 19, to: 7, at: { island: 'glaze', position: [452, 170], yaw: 0 } },
    ],
    dialog: ['石堤尽头那座门楼，就是古代海民留下的「海底神殿之门」。', '门洞被一层蓝光封着，门后的台阶一直通到海底。', '要进去，得学会「潜水」才行……听说镇上那位老潜水员年轻时下去过。'],
  },
  {
    id: 'glaze-keeper',
    name: '灯塔守望人汐',
    title: '琉璃灯塔',
    appearance: { look: 'sailor', palette: { jacket: '#2a6aa8', cap: '#f4f0e6' } },
    schedule: [{ from: 0, to: 24, at: { island: 'glaze', position: [598, 96], yaw: PI }, activity: { kind: 'wander', radius: 2 } }],
    dialog: ['琉璃灯塔照着东边那片深海——那里的海水黑得像墨。', '夜里从灯塔上往下看，深海里偶尔会亮起一圈蓝光。', '老人们说，那是神殿在呼吸。'],
  },
  {
    id: 'glaze-fisher',
    name: '码头渔夫',
    title: '琉璃镇码头',
    appearance: { look: 'fisher', palette: { jacket: '#3f7a9a' } },
    schedule: [{ from: 5, to: 20, at: { island: 'glaze', position: [654, 151], yaw: PI / 2 } }],
    dialog: ['琉璃沙滩的沙子里混着碎玻璃，被浪磨得圆圆的，像糖一样。', '东边深水区别去冲浪钓鱼——鱼线放到底都碰不到海床。'],
  },
  {
    id: 'glaze-kid',
    name: '捡海玻璃的小汀',
    title: '琉璃镇的孩子',
    appearance: { look: 'child-f', palette: { jacket: '#9fe0c8' } },
    schedule: [{ from: 8, to: 18, at: { island: 'glaze', position: [592, 200], yaw: PI / 2 }, activity: { kind: 'wander', radius: 4 } }],
    dialog: ['你看！这块是蓝的，这块是绿的！', '最稀有的是红色海玻璃，我找了三年才找到一块。', '玻璃工坊的大叔会把我捡的海玻璃做成风铃。'],
  },
  {
    id: 'glaze-villager',
    name: '织网阿姨',
    title: '琉璃镇居民',
    appearance: { look: 'villager-f', palette: { jacket: '#5fb8c8' } },
    schedule: [{ from: 7, to: 20, at: { island: 'glaze', position: [470, 152], yaw: 0 }, activity: { kind: 'wander', radius: 5 } }],
    dialog: ['琉璃镇的屋顶瓦片是用海玻璃烧的，下雨天会闪闪发亮。', '道馆的琉璃馆主每天清晨都在喷泉广场练习——她说水的声音能让心静下来。'],
  },
  // ——— 玻璃工坊 ———
  {
    id: 'glaze-glassblower',
    name: '吹玻璃匠岩师傅',
    title: '玻璃工坊',
    appearance: { look: 'hiker', palette: { jacket: '#8a5a3a' } },
    dialogByQuest: [
      { questId: 'side-lily-watervein', when: 'completed', dialog: ['水来了，炉火也稳了。这批玻璃，颜色比往年都亮。'] },
      { questId: 'side-lily-watervein', when: 'active', requires: ['vein-spring-fixed'], setFlags: ['watervein-done'], dialog: ['水来了！冷却池又满了！', '是暴鲤龙堵住了水脉？……你可真行。', '两块水之石，还有这瓶「神秘水滴」，是用第一桶泉水封的。收下吧！'] },
      { questId: 'side-lily-watervein', when: 'active', dialog: ['泉眼在冠军山南麓，琉璃水脉的源头。'] },
      { questId: 'side-lily-watervein', when: 'available', setFlags: ['watervein-start'], dialog: ['唉，炉子要停了。', '工坊冷却用的是琉璃水脉的泉水，可这个月泉水越来越少——今天干脆一滴都没了。', '泉眼在北边冠军山脚下。你去看看是怎么回事好吗？'] },
    ],
    dialog: ['这炉火一千多度，靠近点要小心。', '琉璃镇的玻璃，用的是东海岸的白沙加上海草灰——所以带着海的颜色。', '道馆那座穹顶是我师父那一辈烧的，几十年了，一块都没裂过。'],
  },
  {
    id: 'glaze-glass-apprentice',
    name: '学徒小珀',
    title: '玻璃工坊学徒',
    appearance: { look: 'youngster', palette: { jacket: '#c8703a' } },
    dialog: ['我吹的玻璃球总是歪的……', '师傅说吹玻璃要跟呼吸一样，不能急。'],
  },
  {
    id: 'glaze-glass-clerk',
    name: '店员',
    title: '玻璃工坊柜台',
    appearance: { look: 'clerk', palette: { jacket: '#3f7a9a' } },
    dialog: ['欢迎光临！架子上的玻璃器都是本店手作。', '风铃、浮球、小瓶子……最受欢迎的是装着琉璃沙的瓶中海。'],
  },
  // ——— 老潜水员之家 ———
  {
    id: 'glaze-old-diver',
    name: '老潜水员深叔',
    title: '退休潜水员',
    appearance: { look: 'elder', palette: { jacket: '#2a6aa8', hair: '#d8dce0' } },
    dialogByQuest: [
      { questId: 'side-sea-temple', when: 'completed', dialog: ['你真的走到圣所了？那块会呼吸的晶石……我当年只隔着水幕看了一眼。', '谢谢你，替我把那一眼看完了。'] },
      { questId: 'side-old-diver', when: 'completed', dialog: ['东边颜色最深的海，水面打着旋的地方，就是下潜点。', '神殿前厅的海螺，吹响一只，水幕和暗流就会跟着变。别急，一只一只试。'] },
      { questId: 'side-old-diver', when: 'active', requires: ['diver-compass-found'], dialog: [], story: 'diver-compass-return' },
      { questId: 'side-old-diver', when: 'active', dialog: ['罗盘应该还漂在琉璃沙滩东边的浅湾里。', '那只木匣是我亲手封的，泡不坏。冲浪过去，看见水面上一闪一闪的就是它。'] },
      {
        questId: 'side-old-diver',
        when: 'available',
        setFlags: ['diver-quest-start'],
        dialog: ['琉璃的徽章？哈哈，这下你够格听我讲了。', '四十年前，我在东边深海里见过一座门——真正的海底神殿。石堤那座只是它的影子。', '可惜回来的路上，我把潜水罗盘掉在了琉璃沙滩东边的浅湾里。', '没有那只罗盘，在海沟里会迷路的。帮我找回来，我就把潜水的本事教给你。'],
      },
    ],
    dialog: ['年轻时我潜过东边那片深海。下到三十米，四周一片漆黑。', '然后……我看见了一座门，比石堤那座还大。门上刻着和这边一样的浪纹。', '没有会「潜水」的宝可梦陪着，可千万别去。等你有了本事，再来找我聊聊。'],
  },
  // ———————————————————————————— 彩幽市 ————————————————————————————
  {
    id: 'ever-gate-guard-w',
    name: '联盟门卫',
    title: '精灵联盟',
    appearance: { look: 'guard', palette: { jacket: '#3a5ab8', cap: '#3a5ab8' } },
    schedule: [{ from: 0, to: 24, at: { island: 'glaze', position: [33, -876], yaw: 0 } }],
    dialog: ['这里是精灵联盟大门。', '只有集齐翠澜地区全部 11 枚徽章的训练家，才能通过这扇门。', '进去之后要连续挑战四天王与冠军——准备好了再来。'],
  },
  {
    id: 'ever-gate-guard-e',
    name: '联盟门卫',
    title: '精灵联盟',
    appearance: { look: 'guard', palette: { jacket: '#3a5ab8', cap: '#3a5ab8' } },
    schedule: [{ from: 0, to: 24, at: { island: 'glaze', position: [47, -876], yaw: 0 } }],
    dialog: ['走完冠军之路，来到这里，你已经很了不起了。', '但门后的对手，是整个翠澜最强的训练家。'],
  },
  {
    id: 'ever-guide',
    name: '彩幽市向导',
    title: '欢迎来到彩幽市',
    appearance: { look: 'guide', palette: { cap: '#3a5ab8', jacket: '#3a5ab8' } },
    schedule: [{ from: 0, to: 24, at: { island: 'glaze', position: [45, -704], yaw: PI } }],
    dialog: ['欢迎来到彩幽市——花与荣耀之都！', '宝可梦中心和商店就在大道两侧，北边的旅馆可以免费休息。', '一直往北走过冠军大道，就是精灵联盟大门。'],
  },
  {
    id: 'ever-ace',
    name: '精英训练家薇拉',
    title: '精英训练家',
    appearance: { look: 'camper', palette: { jacket: '#5a7ad8' } },
    schedule: [{ from: 0, to: 24, at: { island: 'glaze', position: [52, -760], yaw: -PI / 2 }, activity: { kind: 'wander', radius: 3 } }],
    dialog: ['我在冠军之路里待了整整一个月。', '出口那段路真的很长……但看到这片花海的时候，觉得一切都值了。'],
  },
  {
    id: 'ever-kid',
    name: '小雀',
    title: '彩幽市居民',
    appearance: { look: 'youngster', palette: { jacket: '#e8c870' } },
    schedule: [{ from: 0, to: 24, at: { island: 'glaze', position: [0, -765], yaw: 0 }, activity: { kind: 'wander', radius: 5 } }],
    dialog: ['等我长大了，也要在冠军大道上立一座星像！', '你也是来挑战联盟的吗？加油！'],
  },
  {
    id: 'ever-gardener',
    name: '园丁老柏',
    title: '彩幽市园丁',
    appearance: { look: 'elder', palette: { jacket: '#5a8a4a', hair: '#d8dce0' } },
    schedule: [{ from: 0, to: 24, at: { island: 'glaze', position: [26, -690], yaw: PI / 2 }, activity: { kind: 'wander', radius: 2 } }],
    dialog: ['这条大道的花坛都是我照料的。', '高原上风大，花却开得特别艳——因为它们每天都看着挑战者从这里走过。'],
  },
  {
    id: 'ever-reporter',
    name: '记者小蓝',
    title: '翠澜周刊',
    appearance: { look: 'villager-f', palette: { jacket: '#d86a4a' } },
    schedule: [{ from: 0, to: 24, at: { island: 'glaze', position: [50, -868], yaw: PI } }],
    dialog: ['我在这里蹲守，等下一位冠军诞生！', '能给我说说你的队伍吗？……啊，等你从联盟出来再说也行。'],
  },
  {
    id: 'ever-hotel-clerk',
    name: '前台',
    title: '训练家旅馆',
    appearance: { look: 'clerk', palette: { jacket: '#3a5ab8' } },
    dialog: ['欢迎光临训练家旅馆。', '联盟挑战者可以免费使用大堂的床铺休息，电脑也随时可以用。'],
  },
  {
    id: 'ever-hotel-ace',
    name: '精英训练家罗恩',
    title: '精英训练家',
    appearance: { look: 'camper', palette: { jacket: '#2a3a7a' } },
    dialog: ['四天王每人擅长一种属性。', '队伍只靠一只主力是行不通的——一定要准备好克制各种属性的宝可梦。'],
  },
  {
    id: 'ever-hotel-veteran',
    name: '老训练家',
    title: '往届挑战者',
    appearance: { look: 'elder', palette: { jacket: '#7a5a3a', hair: '#c8ccd0' } },
    dialog: ['那座奖杯……我年轻时差一点就拿到了。', '输给冠军那天，我在这大堂里坐了一整夜。', '年轻人，别怕输。'],
  },
  {
    id: 'ever-florist',
    name: '花店老板娘',
    title: '彩幽花店',
    appearance: { look: 'villager-f', palette: { jacket: '#8a5ab8' } },
    dialog: ['欢迎光临彩幽花店～', '高原上的花只在海拔九十六米以上开，下山就买不到啦。'],
  },
  {
    id: 'ever-florist-girl',
    name: '花店女儿小堇',
    title: '彩幽花店',
    appearance: { look: 'lass', palette: { jacket: '#f8a8c8' } },
    dialog: ['我每天都会把一朵花放在冠军大道最后那座空白的星像下面。', '妈妈说，总有一天那里会刻上新的名字。'],
  },
];
