/**
 * M1-06 · 萌芽群岛 NPC（萌芽镇 / 萌芽草原 / 翠澜镇 / 港湾市 + 各室内）。
 *
 * - 室内固定位 NPC（无 schedule）的位置写在 config/interiors/sprout.ts 的 `npcs`。
 * - 户外 NPC 用日程：白天在外面活动，夜里回家（不出现）或换地方。
 * - 对话优先级：dialogByQuest → dialogNight/dialogDay → dialog（07-22 §3.5）。
 */
import type { NpcDef } from '@/systems/npcs';

const PI = Math.PI;

export const SPROUT_NPCS: NpcDef[] = [
  // ———————————————————————————— 西岸 · 海崖洞穴 ————————————————————————————
  {
    id: 'cave-explorer',
    name: '岩生',
    title: '洞穴探险家',
    appearance: { look: 'hiker', palette: { jacket: '#b5793a', pants: '#4a4a3a', cap: '#3d5a3a' } },
    activity: { kind: 'stand' },
    schedule: [
      { from: 6, to: 20, at: { island: 'sprout', position: [-256.5, 115.5], yaw: 2.03 }, activity: { kind: 'stand' } },
      { from: 20, to: 23, at: { island: 'sprout', position: [-252, 122], yaw: 2.6 }, activity: { kind: 'wander', radius: 2 } },
    ],
    dialog: [
      '看到崖脚那个洞口了吗？里面隐约有光在闪。',
      '可惜洞口被一块裂开的大石头堵死了，我敲了三天都敲不动。',
      '听说能骑着格斗、岩石或地面属性的宝可梦把这种石头撞碎……',
      '等你有了那种本事，可一定要进去看看，再回来告诉我里面有什么！',
    ],
    dialogNight: ['天黑了，崖下的浪声听起来怪吓人的。', '洞里好像有什么东西在发光……是水晶吗？'],
  },
  // ———————————————————————————— 萌芽镇 · 室内 ————————————————————————————
  {
    id: 'mom',
    name: '妈妈',
    appearance: { look: 'mom' },
    activity: { kind: 'wander', radius: 1.2 },
    dialogByQuest: [
      { questId: 'main-get-starter', when: 'active', dialog: ['早上好！木兰博士一早就来过电话了。', '她说研究所那边准备好了，让你过去一趟。', '别让博士等太久哦。'] },
      { questId: 'main-gym-verdant', when: 'active', dialog: ['你的宝可梦看起来很有精神呢！', '翠澜镇就在萌芽草原的南边，道馆在湖中央。', '累了就回家休息，妈妈给你们留了点心。'] },
    ],
    dialogNight: ['这么晚了还要出门？', '夜里草原上会出现白天见不到的宝可梦，要小心哦。'],
    dialog: ['路上小心！', '记得常回家看看。'],
  },
  {
    id: 'magnolia',
    name: '木兰博士',
    title: '宝可梦博士',
    appearance: { look: 'professor' },
    dialogByQuest: [
      { questId: 'side-cloud-mail', when: 'active', unless: ['mail-magnolia'], setFlags: ['mail-magnolia'], dialog: ['云雀镇寄来的信？是雷鸣大学的白桦教授！', '……冰川遗迹里发现了蓝色的碎片？了不起，你帮我回个话：研究所全力支持。', '辛苦你跑这么远啦。'] },
      // M2 · 碧潮支线「古代石板解读」
      {
        questId: 'side-ancient-tablet',
        when: 'active',
        setFlags: ['ancient-tablet-delivered'],
        dialog: ['这是……碧潮群岛矿洞里挖出来的石板？！', '这些文字……和研究所收藏的古代文献是同一种！', '「五岛升于海，七片守其约。」……七片——是异变碎片的数量吗？', '太了不起了！我已经把碧潮群岛的生态数据补进你的图鉴里了。', '这是研究经费的一部分，一定要收下！'],
      },
      { questId: 'side-ancient-tablet', when: 'completed', dialog: ['石板的解读还在继续。', '七块碎片、五座岛……群岛的历史比我们想象的还要古老。'] },
      {
        questId: 'main-get-starter',
        when: 'active',
        dialog: ['你来啦！我是木兰，研究翠澜群岛宝可梦生态的博士。', '最近群岛各处都出现了奇怪的「异变」，我需要可靠的帮手。', '桌上的精灵球里有三只宝可梦——木木枭、火球鼠、水跃鱼。', '选一只作为你的伙伴吧！'],
        story: 'starter-choice',
      },
      { questId: 'main-gym-verdant', when: 'active', dialog: ['你和伙伴相处得怎么样？', '翠澜镇的馆主沧澜擅长水属性。', '湖心道馆里的水位会变化，仔细观察再行动。', '对了，宝可梦累了就用我身后的恢复机吧，随时都可以用。'] },
      { questId: 'main-harbor-ferry', when: 'active', dialog: ['听说港湾市的渡船停航了……', '异变是不是已经影响到海上了？去看看情况吧。'] },
    ],
    dialog: ['群岛的异变还有很多谜团。', '图鉴记录得越多，我们离真相就越近。'],
  },
  {
    id: 'lab-aide-1',
    name: '研究员小周',
    title: '研究助手',
    appearance: { look: 'aide' },
    dialog: ['这台机器在记录群岛各地的能量波动。', '最近的读数……有点不太对劲。'],
    dialogNight: ['又要加班了……', '博士总是比我们来得早、走得晚。'],
    dialogByQuest: [
      { questId: 'side-dex-first-page', when: 'completed', dialog: ['群岛还有很多宝可梦等着你去登记。', '图鉴每多一页，我们离群岛异变的真相就更近一步。'] },
      { questId: 'side-dex-first-page', when: 'active', requires: ['dexpage-caught'], setFlags: ['dexpage-done'], dialog: ['哇，3 只都登记上了！', '看，图鉴的第一页已经亮起来了。', '这些精灵球和伤药送给你，继续加油！'] },
      { questId: 'side-dex-first-page', when: 'active', dialog: ['捕捉的诀窍：先把对手的 HP 打到红色，再扔精灵球。', '睡眠或麻痹状态下的宝可梦也更容易抓到哦。'] },
      { questId: 'side-dex-first-page', when: 'available', setFlags: ['dexpage-start'], dialog: ['你就是刚领到宝可梦的新训练家吧？', '图鉴的第一页最让人激动了！', '去草丛里捕捉 3 只宝可梦吧——削弱它们的体力再扔球，成功率会高很多。', '抓到了就回来给我看看！'] },
    ],
  },
  {
    id: 'lab-aide-2',
    name: '研究员阿芳',
    title: '研究助手',
    appearance: { look: 'aide', palette: { hair: '#8a4b2a' }, style: { hair: 'pony', glasses: false } },
    activity: { kind: 'wander', radius: 1.5 },
    dialogByQuest: [
      { questId: 'side-partner-growth', when: 'completed', dialog: ['进化是宝可梦和训练家一起成长的证明。'] },
      { questId: 'side-partner-growth', when: 'active', requires: ['growth-evolved'], setFlags: ['growth-done'], dialog: ['进化了？！快让我看看！', '……太棒了，这组数据非常珍贵。', '这是研究所的谢礼，请收下！'] },
      { questId: 'side-partner-growth', when: 'active', dialog: ['宝可梦升到一定等级就会进化。', '打倒野生宝可梦能获得经验，多去湖畔转转吧。'] },
      { questId: 'side-partner-growth', when: 'available', setFlags: ['growth-start'], dialog: ['你拿到徽章了？恭喜！', '我在研究宝可梦的进化——它们在战斗中成长，到了某个时刻就会突然变化。', '多和野生宝可梦对战积累经验，让一只宝可梦进化后回来告诉我！'] },
      { questId: 'main-get-starter', when: 'active', dialog: ['三只宝可梦都很期待见到你。', '木木枭沉稳、火球鼠胆小但勇敢、水跃鱼特别黏人。'] }],
    dialog: ['草丛里的宝可梦会被脚步声吓到。', '慢慢走、蹲低一点，就能靠近它们。'],
  },
  {
    id: 'elder-pu',
    name: '蒲婆婆',
    title: '药草师',
    appearance: { look: 'elder' },
    schedule: [
      // 上午在自家门前的药草园
      { from: 7, to: 11, at: { island: 'sprout', position: [-158, 386], yaw: PI }, activity: { kind: 'wander', radius: 2.5 } },
      { from: 11, to: 7, at: { interior: 'sprout-elder-house', room: 'main', position: [0.9, 0.3], yaw: -PI / 2 } },
    ],
    // 计划文档 §9.4：培育家导师。对话后打开培育家菜单（等级 / 个体值评估 / 培育屋）
    service: { kind: 'breeder' },
    dialogByQuest: [
      // ——— 培育家之路（放在药草支线前面：药草支线完成后的对话会一直匹配） ———
      {
        questId: 'side-breeder-road-1',
        when: 'available',
        dialog: ['哟，拿到徽章啦？婆婆就知道你有出息。', '光会打架可不算好训练家。种树果、做方块、照顾宝可梦的心情——这些婆婆年轻时可是行家。', '要不要跟婆婆学学，当个「培育家」？', '先去田里收两次树果；成了 2 级培育家，你家那台方块机就转得动了。做个方块喂给宝可梦，再回来告诉婆婆。'],
        setFlags: ['breeder-start'],
      },
      {
        questId: 'side-breeder-road-1',
        when: 'active',
        requires: ['breeder1-fed'],
        dialog: ['看你的宝可梦，眼睛都亮了——方块很合它的口味吧？', '好，从今天起你就是婆婆的培育家学徒了。', '以后收获、做方块、喂宝可梦都会长本事。到了 3 级，翠澜镇和港湾市的公共田就能租了。'],
        setFlags: ['breeder-road-1'],
      },
      { questId: 'side-breeder-road-1', when: 'active', dialog: ['田里的树果收了吗？方块机要 2 级培育家才转得动哦。', '做好方块，打开背包里的「方块盒」喂给宝可梦。'] },
      {
        questId: 'side-breeder-road-2',
        when: 'available',
        dialog: ['5 级了？进步真快。', '婆婆家后屋空着，就给你当「培育屋」吧——宝可梦寄放在这儿，婆婆帮你照看、陪它练习。', '你寄放一只再领回来试试；另外宝可梦中心的工坊有个叫阿铁的手艺人，拿采来的素材找他合成点东西。'],
        setFlags: ['breeder2-start'],
      },
      {
        questId: 'side-breeder-road-2',
        when: 'active',
        requires: ['breeder2-daycare', 'breeder2-crafted'],
        dialog: ['培育屋和工坊都用过了吧。', '采集、种植、培育、合成，样样连在一起——这就是培育家的日子。', '这几颗珍珠和变异肥拿着，种出稀罕的树果来给婆婆瞧瞧。'],
        setFlags: ['breeder-road-2'],
      },
      { questId: 'side-breeder-road-2', when: 'active', dialog: ['跟婆婆说「培育屋」就能寄放宝可梦。', '工坊在宝可梦中心进门左手边。'] },
      {
        questId: 'side-breeder-road-3',
        when: 'available',
        dialog: ['7 级啦。婆婆教你最后一门手艺：性格薄荷。', '头目宝可梦身上掉下的鳞片，配上两颗稀有的树果，阿铁就能做出改变宝可梦性格的薄荷。', '做出一片，再成为 10 级培育家——到时候，婆婆就把「翠澜培育大师」的名号交给你。'],
        setFlags: ['breeder3-start'],
      },
      {
        questId: 'side-breeder-road-3',
        when: 'active',
        requires: ['breeder3-mint', 'breeder-lv10'],
        dialog: ['……好，好。婆婆没看错人。', '从今天起，你就是「翠澜培育大师」。', '这顶金王冠是婆婆年轻时赢来的，留给你吧。'],
        setFlags: ['breeder-road-3'],
      },
      { questId: 'side-breeder-road-3', when: 'active', dialog: ['头目之鳞要打倒或捕获头目才拿得到。', '稀有树果是半减果和风味果，野外树果树和变异肥都能弄到。'] },
      {
        questId: 'side-elder-herbs',
        when: 'available',
        dialog: ['哎呀，好孩子，能帮婆婆一个忙吗？', '翠澜湖畔长着一种叶子泛蓝的药草，婆婆腿脚不便……', '帮我采 3 株回来吧，婆婆会好好谢你的。'],
        setFlags: ['herbs-quest-start'],
      },
      {
        questId: 'side-elder-herbs',
        when: 'active',
        requires: ['herbs-collected'],
        dialog: ['哎呀，3 株翠澜药草，一株不少！', '叶子新鲜，采得真仔细。', '这些解毒药你拿着，出门在外用得上。'],
        setFlags: ['herbs-delivered'],
      },
      { questId: 'side-elder-herbs', when: 'active', dialog: ['翠澜药草长在湖边潮湿的地方。', '叶子背面是蓝色的，别采错了哦。'] },
      { questId: 'side-elder-herbs', when: 'completed', dialog: ['多亏了你，药膏做好了。', '宝可梦中了毒，就给它用解毒药吧。'] },
    ],
    // 计划文档 §9.3：药草支线完成后教你种树果（开放自家后院 4 块田）
    gift: {
      item: 'watering-can',
      qty: 1,
      flag: 'farm-unlocked',
      requires: ['herbs-delivered'],
      lines: ['好孩子，上次的药草帮了婆婆大忙。', '婆婆年轻时可是种树果的好手——你家后院那几块田，婆婆早就帮你翻好土啦。', '这个喷壶和几颗树果给你，拿回去种种看吧。'],
      extra: [
        { item: 'oran-berry', qty: 3 },
        { item: 'cheri-berry', qty: 2 },
        { item: 'pecha-berry', qty: 2 },
        { item: 'growth-mulch', qty: 1 },
      ],
      after: ['种的时候把树果埋进田里，按 E 照料。', '每个阶段——发芽、长高、开花——至少浇一次水，收成才好；下雨天老天爷会帮你浇。', '长了杂草、生了虫就赶紧清掉，草系、虫系的宝可梦也很会帮忙。', '发芽前施点肥更好：成长肥长得快，丰收肥结得多。港湾市老吴的果摊有卖。'],
    },
    dialogDay: ['早上的露水最养药草了。'],
    dialog: ['年轻人，出门在外要照顾好自己和宝可梦。'],
  },

  // ———————————————————————————— 萌芽镇 · 户外 ————————————————————————————
  {
    id: 'sprout-kid',
    name: '小翼',
    title: '萌芽镇的孩子',
    appearance: { look: 'child-m' },
    schedule: [{ from: 8, to: 18, at: { island: 'sprout', position: [-92, 368], yaw: 0 }, activity: { kind: 'wander', radius: 6 } }],
    dialogByQuest: [{ questId: 'main-get-starter', when: 'active', dialog: ['你今天要去领宝可梦吗？好羡慕！', '等我长大了，也要去博士那里！'] }],
    dialog: ['我昨天在草原上看到一只波波！', '它飞得好快，一下子就不见了。'],
  },
  {
    id: 'sprout-girl',
    name: '小铃',
    title: '萌芽镇居民',
    appearance: { look: 'villager-f' },
    schedule: [
      { from: 7, to: 12, at: { island: 'sprout', position: [-34, 330], yaw: PI / 2 }, activity: { kind: 'stand' } },
      { from: 12, to: 19, at: { island: 'sprout', position: [-60, 362], yaw: 0 }, activity: { kind: 'wander', radius: 4 } },
    ],
    dialog: ['研究所的木兰博士很温柔，也很厉害。', '听说她年轻时走遍了五座岛。'],
    dialogByQuest: [{ questId: 'main-get-starter', when: 'completed', dialog: ['哇，这是你的宝可梦吗？好可爱！', '要好好对待它哦。'] }],
  },
  {
    id: 'sprout-gardener',
    name: '老林',
    title: '园丁',
    appearance: { look: 'villager-m', palette: { jacket: '#6e8f3a', cap: '#c9a25c' }, style: { hat: 'bucket', apron: true }, accent: '#8a6a42' },
    schedule: [
      { from: 6, to: 17, at: { island: 'sprout', position: [-138, 378], yaw: -PI / 2 }, activity: { kind: 'patrol', path: [[0, 0], [6, 0], [6, 3], [0, 3]] } },
      { from: 17, to: 21, at: { island: 'sprout', position: [-70, 358], yaw: 0 }, activity: { kind: 'stand' } },
    ],
    dialogDay: ['花坛里有时会躲着小宝可梦。', '别担心，它们不会弄坏花的——大概。'],
    dialogNight: ['忙了一天，坐下来看看星星。', '萌芽镇的夜空是全群岛最干净的。'],
    dialog: ['今天天气不错。'],
  },
  {
    id: 'sprout-dock-keeper',
    name: '老船工 阿海',
    title: '码头管理员',
    appearance: { look: 'sailor', palette: { hair: '#dcdcdc' }, style: { beard: true } },
    schedule: [{ from: 5, to: 20, at: { island: 'sprout', position: [-70, 440], yaw: 0 }, activity: { kind: 'stand' } }],
    dialogByQuest: [{ questId: 'main-harbor-ferry', when: 'completed', dialog: ['渡船恢复了？太好了！', '以后坐船就能去别的岛啦。'] }],
    dialog: ['这里的小船只能在近海转转。', '想去别的岛，得去港湾市坐渡船。'],
  },

  // ———————————————————————————— 萌芽草原（1 号路） ————————————————————————————
  {
    id: 'route1-youngster',
    name: '短裤小子 阿健',
    title: '训练家',
    appearance: { look: 'child-m', palette: { cap: '#3d8fd9', jacket: '#f2b541', pants: '#3d5a8a' } },
    schedule: [{ from: 7, to: 19, at: { island: 'sprout', position: [-56, 250], yaw: PI }, activity: { kind: 'wander', radius: 4 } }],
    dialog: ['草丛里的宝可梦有时会突然冲出来！', '跑步会吓跑胆小的宝可梦，慢慢走更容易遇到它们。'],
    dialogByQuest: [
      { questId: 'side-trainer-road', when: 'completed', dialog: ['下次我一定会变得更强，再来挑战你！'] },
      { questId: 'side-trainer-road', when: 'active', requires: ['trainerroad-won'], setFlags: ['trainerroad-done'], dialog: ['真的赢了 3 场？！', '你比我想象的还厉害……', '这些超级球给你，这是训练家之间的尊重！'] },
      { questId: 'side-trainer-road', when: 'active', dialog: ['和训练家对上视线就会开战，躲不掉的！', '打之前记得在宝可梦中心回复一下。'] },
      { questId: 'side-trainer-road', when: 'available', setFlags: ['trainerroad-start'], dialog: ['喂！你也是训练家吧？', '草原上的训练家都在等人挑战！', '去和 3 位训练家对战，赢了再回来找我——让我看看你有多强！'] },
      { questId: 'main-get-starter', when: 'active', dialog: ['没有宝可梦的话，最好别走进高高的草丛哦。', '野生宝可梦可是会扑上来的！'] }],
  },
  {
    id: 'route1-bugcatcher',
    name: '捕虫少年 小树',
    title: '训练家',
    appearance: { look: 'bug-catcher' },
    schedule: [{ from: 6, to: 19, at: { island: 'sprout', position: [-34, 168], yaw: -PI / 2 }, activity: { kind: 'wander', radius: 3 } }],
    dialogDay: ['早上的树林里绿毛虫最多了！', '它们会吐丝，小心别被缠住。'],
    dialog: ['虫系宝可梦进化得很快，很值得培养！'],
  },
  {
    id: 'route1-hiker',
    name: '登山客 大石',
    title: '登山者',
    appearance: { look: 'hiker' },
    schedule: [{ from: 0, to: 24, at: { island: 'sprout', position: [-24, 102], yaw: PI }, activity: { kind: 'stand' } }],
    dialogNight: ['夜里的草原会冒出走路草和小拉达。', '要找它们的话，现在正是时候。'],
    dialog: ['我在这里歇歇脚。', '往南走就是翠澜镇，往西能看到幻影之森——那边经常起雾。'],
    dialogByQuest: [
      { questId: 'side-forest-whisper', when: 'completed', dialog: ['今晚的森林安静多了。', '我也终于能睡个好觉了。'] },
      { questId: 'side-forest-whisper', when: 'active', requires: ['whisper-calm'], setFlags: ['whisper-done'], dialog: ['原来是一群受惊的野生宝可梦在林子里乱跑……', '你把它们安抚下来了？了不起！', '这些拿去吧，夜路上用得着。'] },
      { questId: 'side-forest-whisper', when: 'active', dialog: ['足迹只在夜里才会发光。', '在原地休息、或者回家睡一觉就能等到天黑。'] },
      { questId: 'side-forest-whisper', when: 'available', setFlags: ['whisper-start'], dialog: ['小家伙，你听说过幻影之森的低语吗？', '一到夜里，林子里就会传来沙沙的声音，还有发光的足迹。', '等天黑了，沿着林道走进去看看吧。白天可是什么都看不到的。'] },
    ],
  },

  // ———————————————————————————— 翠澜镇 ————————————————————————————
  {
    id: 'nurse',
    name: '乔伊',
    title: '宝可梦中心护士',
    appearance: { look: 'nurse' },
    service: { kind: 'heal' },
    dialog: ['欢迎来到宝可梦中心！'],
    dialogNight: ['晚上好，欢迎来到宝可梦中心。', '宝可梦中心全天开放哦。'],
  },
  {
    id: 'center-visitor',
    name: '旅行者 美穗',
    title: '旅行者',
    appearance: { look: 'villager-f', palette: { jacket: '#d96b8a', hair: '#2b2b3b' }, style: { hair: 'long', bag: true } },
    dialog: ['宝可梦中心随时都可以免费治疗宝可梦。', '出发去冒险之前，一定要先来这里。'],
    dialogByQuest: [
      { questId: 'side-travel-prep', when: 'completed', dialog: ['旅行的意义，就在于路上遇到的一切。'] },
      { questId: 'side-travel-prep', when: 'active', requires: ['travelprep-bought'], setFlags: ['travelprep-done'], dialog: ['很好，宝可梦精神满满，背包也装满了。', '这些是我旅行剩下的好药，送给你。', '一路顺风！'] },
      { questId: 'side-travel-prep', when: 'active', dialog: ['宝可梦中心在左边柜台，友好商店就在镇子南边。', '伤药和精灵球都是必需品哦。'] },
      { questId: 'side-travel-prep', when: 'available', setFlags: ['travelprep-start'], dialog: ['你要出远门吗？我教你旅行前的两件事。', '第一，把宝可梦交给乔伊小姐回复。', '第二，去隔壁的友好商店补点道具。', '都做完了再来找我吧！'] },
    ],
  },
  {
    id: 'clerk',
    name: '店员',
    title: '友好商店',
    appearance: { look: 'clerk' },
    service: { kind: 'shop', shop: 'cuilan-mart' },
    dialog: ['欢迎光临友好商店！'],
  },
  {
    // 计划文档 §6：想起招式的人（翠澜镇宝可梦中心）
    id: 'move-reminder',
    name: '回想老人 忆翁',
    title: '想起招式的人',
    appearance: { look: 'elder', palette: { jacket: '#7a5aa6', hair: '#e8e4dc' } },
    service: { kind: 'recall' },
    dialog: ['呵呵……宝可梦忘掉的招式，其实都还藏在心底。', '给我一片心之鳞片，或者 1000 円，我就帮它想起来。'],
  },
  {
    id: 'workshop-tie',
    name: '工匠 阿铁',
    title: '工坊',
    appearance: { look: 'hiker', palette: { jacket: '#8a5a3a', pants: '#4a4f5c' }, style: { apron: true, hat: 'bandana' }, accent: '#c9a25c' },
    service: { kind: 'workshop' },
    dialog: ['工坊开张！药草、蘑菇、矿石、贝壳……拿来什么，我就给你敲出什么。', '配方多少，看你培育家的本事——蒲婆婆的徒弟，我阿铁另眼相看。'],
  },
  {
    id: 'mart-shopper',
    name: '主妇 秋子',
    title: '顾客',
    appearance: { look: 'villager-f', palette: { jacket: '#9c7bd1' }, style: { hair: 'bun', apron: true }, accent: '#f4efe6' },
    dialog: ['伤药买多少都不嫌多。', '精灵球也要多备几个——遇到喜欢的宝可梦可不能错过。'],
  },
  {
    id: 'cuilan-rumor-girl',
    name: '少女 雾音',
    title: '翠澜镇居民',
    appearance: { look: 'villager-f', palette: { jacket: '#6a5acd', hair: '#1f1f2a' }, style: { hair: 'long' } },
    schedule: [
      { from: 7, to: 19, at: { island: 'sprout', position: [-26, 6], yaw: -PI / 2 }, activity: { kind: 'stand' } },
      { from: 19, to: 23, at: { island: 'sprout', position: [-34, -2], yaw: 0 }, activity: { kind: 'stand' } },
    ],
    dialogByQuest: [
      {
        questId: 'side-zorua-forest',
        when: 'available',
        dialog: ['你相信吗？我在幻影之森里看到了一个「人」……', '可是一眨眼，它就变成了一只黑色的小狐狸！', '雾气会改变森林里的路，只有跟着它的脚印才不会迷路。', '你能去帮我看看吗？'],
        setFlags: ['zorua-quest-start'],
      },
      { questId: 'side-zorua-forest', when: 'active', dialog: ['幻影之森在萌芽草原的西边。', '起雾的时候，那只小狐狸最常出现。'] },
      { questId: 'side-zorua-forest', when: 'completed', dialog: ['原来是索罗亚！它会变成别人的样子。', '它愿意跟着你，说明它很信任你呢。'] },
    ],
    dialogNight: ['晚上的森林更可怕了……', '可我总觉得，那只小狐狸在等人。'],
    dialog: ['幻影之森里总有奇怪的传闻。'],
  },
  {
    id: 'cuilan-old-man',
    name: '钓鱼老伯',
    title: '翠澜镇居民',
    appearance: { look: 'elder', palette: { jacket: '#5b7c99' }, style: { hat: 'bucket', cane: false } },
    schedule: [{ from: 6, to: 21, at: { island: 'sprout', position: [-62, -36], yaw: PI / 2 }, activity: { kind: 'stand' } }],
    dialog: ['翠澜湖的水特别清。', '湖心的道馆，是我年轻时和大家一起盖起来的。'],
    dialogByQuest: [
      { questId: 'side-lake-light', when: 'completed', dialog: ['湖底的光还在闪着呢。', '有空多去湖上看看吧。'] },
      { questId: 'side-lake-light', when: 'active', requires: ['lakelight-fished'], setFlags: ['lakelight-done'], dialog: ['什么？湖底下是一群发光的宝可梦？', '原来如此……我年轻时看到的光就是它们啊。', '谢谢你帮我解开了这个心结，这是一点心意。'] },
      { questId: 'side-lake-light', when: 'active', dialog: ['光点在湖心道馆的东南边，离岸有段距离。', '钓鱼竿记得带上，在水上也能钓。'] },
      { questId: 'side-lake-light', when: 'available', setFlags: ['lakelight-start'], dialog: ['你会冲浪了？那我跟你说个秘密。', '夜里翠澜湖上会冒出一点微光，几十年了都这样。', '你骑着宝可梦去那儿看看，顺便钓一次鱼——说不定能钓到光的主人。'] },
      { questId: 'main-gym-verdant', when: 'completed', dialog: ['你赢了沧澜？了不起！', '有了冲浪的本领，就能去湖对岸看看了。'] }],
  },
  {
    id: 'gym-bridge-guard',
    name: '道馆职员',
    title: '翠澜道馆',
    appearance: { look: 'guard' },
    schedule: [{ from: 0, to: 24, at: { island: 'sprout', position: [16, -51], yaw: -PI / 2 }, activity: { kind: 'stand' } }],
    dialogByQuest: [
      { questId: 'main-get-starter', when: 'active', dialog: ['道馆正在准备中。', '先去萌芽镇找木兰博士领取宝可梦吧。'] },
      { questId: 'main-gym-verdant', when: 'active', dialog: ['挑战者吗？请过桥。', '馆主沧澜在湖心等着你。'] },
      { questId: 'main-gym-verdant', when: 'completed', dialog: ['恭喜你拿到翠澜徽章！'] },
    ],
    dialog: ['这座桥通往翠澜道馆。'],
  },

  // ———————————————————————————— 翠澜道馆 ————————————————————————————
  {
    id: 'gym-guide',
    name: '道馆向导',
    title: '翠澜道馆',
    appearance: { look: 'guide' },
    dialogByQuest: [
      { questId: 'main-gym-verdant', when: 'active', dialog: ['嘿，未来的冠军！', '沧澜用的是水属性宝可梦。草属性和电属性的招式会很有效！', '池子里的水位由阀门控制，墙上的告示牌写着规则。', '想清楚先转哪一个阀门，别把自己困在岛上！'] },
      { questId: 'main-gym-verdant', when: 'completed', dialog: ['漂亮的一战！', '群岛上还有更多道馆在等着你。'] },
    ],
    dialog: ['欢迎来到翠澜道馆！'],
  },
  {
    id: 'canglan',
    name: '沧澜',
    title: '翠澜道馆馆主',
    appearance: { look: 'leader-water' },
    trainer: 'gym-cuilan-leader',
    dialogByQuest: [
      { questId: 'main-gym-verdant', when: 'completed', dialog: ['你已经证明了自己。', '带着翠澜徽章，去更远的海上看看吧。'] },
    ],
    dialog: ['等你有了宝可梦，再来挑战我吧。'],
  },
  {
    id: 'gym-trainer-1',
    name: '阿浪',
    title: '泳裤小伙',
    appearance: { look: 'swimmer' },
    trainer: 'gym-cuilan-1',
    dialog: ['池子里的水位是连动的：放掉水，石栈道就露出来了。', '不过木筏也会跟着沉下去，别把自己困在岛上哦。'],
    dialogByQuest: [{ questId: 'main-gym-verdant', when: 'completed', dialog: ['你连馆主都赢了……我服了！'] }],
  },
  {
    id: 'gym-trainer-2',
    name: '小汐',
    title: '比基尼大姐',
    trainer: 'gym-cuilan-2',
    appearance: { look: 'swimmer', palette: { hair: '#e8b04a', jacket: '#e8484a' }, style: { hair: 'pony' } },
    dialog: ['再把水位升回去，木筏就会浮到馆主台前。', '沧澜大人的暴鲤龙非常凶猛，小心它的威吓。'],
  },

  // ———————————————————————————— 港湾市 ————————————————————————————
  {
    id: 'harbor-fisherman',
    name: '渔夫 老陈',
    title: '渔夫',
    appearance: { look: 'fisher' },
    gift: {
      item: 'old-rod',
      qty: 1,
      flag: 'got-old-rod',
      lines: ['哦？是个年轻的训练家啊。', '钓鱼可是港湾市的传统！这根旧钓竿送给你，拿去试试手气吧。'],
      after: ['面朝水面按 F 就能抛竿。', '按住蓄力、松开抛出；浮漂猛地一沉的瞬间赶紧拉竿！', '收线的时候别太用力，线绷太紧可是会断的。', '码头边冒泡的地方，鱼特别多。'],
    },
    schedule: [
      { from: 5, to: 19, at: { island: 'sprout', position: [438, 110], yaw: PI / 2 }, activity: { kind: 'stand' } },
      { from: 19, to: 22, at: { island: 'sprout', position: [372, 60], yaw: 0 }, activity: { kind: 'stand' } },
    ],
    dialogByQuest: [
      {
        questId: 'side-fisherman-lost',
        when: 'available',
        dialog: ['唉，昨天出海遇上怪浪，钓具箱被卷走了……', '那可是我爷爷传下来的！', '如果你能去外海找找，我就把我的好钓竿送给你。'],
        setFlags: ['fisher-quest-start'],
      },
      {
        questId: 'side-fisherman-lost',
        when: 'active',
        requires: ['fisher-tackle-found'],
        dialog: ['这、这是……我的钓具箱！', '箱子上的「陈」字还是我爷爷亲手刻的。', '说好的，这根好钓竿送给你！'],
        setFlags: ['fisher-tackle-returned'],
      },
      { questId: 'side-fisherman-lost', when: 'active', dialog: ['钓具箱应该漂到港湾外海去了，大概在码头东南边。', '学会冲浪之后才能到那里。'] },
      { questId: 'side-fisherman-lost', when: 'completed', dialog: ['真的是我的钓具箱！谢谢你！', '好钓竿能钓到更大的宝可梦，好好用它。'] },
    ],
    dialogNight: ['收工啦，明天再出海。'],
    dialog: ['钓鱼要有耐心。'],
  },
  {
    id: 'contest-host',
    name: '主持人 阿潮',
    title: '钓鱼大赛',
    appearance: { look: 'villager-m', palette: { jacket: '#e8484a', cap: '#ffffff' }, style: { hat: 'cap', bag: false, glasses: true } },
    schedule: [{ from: 8, to: 18, at: { island: 'sprout', position: [430, 98], yaw: PI }, activity: { kind: 'stand' } }],
    dialogByQuest: [
      {
        questId: 'side-fishing-contest',
        when: 'available',
        dialog: ['港湾市钓鱼挑战赛，现在开始报名！', '规则很简单：钓到鲤鱼王、玛瑙水母，还有夜里才出现的海星星。', '全部完成就来找我领奖！'],
        setFlags: ['fishing-contest-start'],
      },
      {
        questId: 'side-fishing-contest',
        when: 'active',
        requires: ['contest-staryu'],
        dialog: ['鲤鱼王、玛瑙水母、海星星——全部到齐！', '恭喜你，本届钓鱼大赛的冠军就是你！'],
        setFlags: ['fishing-contest-done'],
      },
      { questId: 'side-fishing-contest', when: 'active', dialog: ['加油！要按顺序钓哦：鲤鱼王、玛瑙水母，最后是海星星。', '海星星只在夜里出现，而且要用好钓竿。'] },
      { questId: 'side-fishing-contest', when: 'completed', dialog: ['冠军就是你！厉害钓竿用得还顺手吗？', '下一届大赛也要来参加哦！'] },
    ],
    dialog: ['钓鱼大赛需要有钓竿才能参加哦。'],
  },
  {
    id: 'ferry-clerk',
    name: '渡船管理员',
    title: '渡船码头',
    appearance: { look: 'sailor', palette: { jacket: '#2f4f7f' } },
    schedule: [{ from: 6, to: 22, at: { island: 'sprout', position: [438, 26], yaw: -PI / 2 }, activity: { kind: 'stand' } }],
    dialogByQuest: [
      {
        questId: 'main-harbor-ferry',
        when: 'active',
        requires: ['lighthouse-relit'],
        dialog: ['灯塔亮了！我在码头上都看见了！', '有灯塔指引，船长也同意恢复航行了。', '这是渡船船票——以后拿着它就能随时坐船。'],
        setFlags: ['ferry-route-opened'],
      },
      {
        questId: 'main-harbor-ferry',
        when: 'active',
        requires: ['ferry-clerk-talked'],
        dialog: ['灯塔守老周就在北边的灯塔那里。', '只要灯塔重新亮起来，船就能出港了。'],
      },
      {
        questId: 'main-harbor-ferry',
        when: 'active',
        dialog: ['抱歉，渡船暂时停航了。', '外海最近总有奇怪的漩涡，还起了怪雾……', '更糟的是，灯塔前几天突然熄灭了，船长说没有灯塔指引太危险。', '你能去灯塔问问老周是怎么回事吗？'],
        setFlags: ['ferry-clerk-talked'],
      },
      { questId: 'main-harbor-ferry', when: 'completed', dialog: ['渡船恢复运行了！', '不过去碧潮群岛的正式航班还在排期……', '会冲浪的话，从码头往东横渡水路 1 也能看到碧潮群岛。'] },
    ],
    dialog: ['这里是港湾市渡船码头。'],
  },
  {
    id: 'harbor-sailor',
    name: '水手 大海',
    title: '水手',
    appearance: { look: 'sailor' },
    schedule: [
      { from: 7, to: 18, at: { island: 'sprout', position: [398, 42], yaw: 0 }, activity: { kind: 'wander', radius: 7 } },
      { from: 18, to: 23, at: { island: 'sprout', position: [362, 30], yaw: PI / 2 }, activity: { kind: 'stand' } },
    ],
    dialog: ['我跑过五座岛的航线。', '碧潮群岛的海水是翡翠色的，你一定要去看看！'],
    dialogNight: ['喝完这杯就回船上睡觉。'],
  },
  {
    id: 'harbor-kid',
    name: '小男孩 阿帆',
    title: '港湾市的孩子',
    appearance: { look: 'child-m', palette: { cap: '#2f8f6f', jacket: '#ffffff' }, style: { hat: 'sailor' } },
    schedule: [{ from: 9, to: 17, at: { island: 'sprout', position: [368, 52], yaw: 0 }, activity: { kind: 'wander', radius: 5 } }],
    dialog: ['我长大要当船长！', '灯塔那边晚上会亮起来，超漂亮的。'],
  },
  {
    id: 'lighthouse-keeper',
    name: '灯塔守 老周',
    title: '灯塔守',
    appearance: { look: 'elder', palette: { jacket: '#2f3a5a' }, style: { hat: 'sailor', cane: false, beard: true } },
    schedule: [{ from: 0, to: 24, at: { island: 'sprout', position: [418, -50], yaw: PI }, activity: { kind: 'stand' } }],
    dialogByQuest: [
      {
        questId: 'main-harbor-ferry',
        when: 'active',
        requires: ['lighthouse-relit'],
        dialog: ['灯塔又亮起来了，真是多亏了你。', '快去告诉渡船管理员吧！'],
      },
      {
        questId: 'main-harbor-ferry',
        when: 'active',
        requires: ['lighthouse-keeper-asked'],
        dialog: ['控制箱就在灯塔脚下。', '把盐霜擦干净、重新合上电闸就行。'],
      },
      {
        questId: 'main-harbor-ferry',
        when: 'active',
        requires: ['ferry-clerk-talked'],
        dialog: [
          '渡船管理员让你来的？唉……',
          '前几天夜里，海上漫过来一阵怪雾，第二天灯塔就熄了。',
          '控制箱上结满了白花花的盐霜，电闸被卡死，我这把老骨头怎么也推不动。',
          '年轻人，你能帮我把灯塔重新点亮吗？',
        ],
        setFlags: ['lighthouse-keeper-asked'],
      },
      { questId: 'main-harbor-ferry', when: 'completed', dialog: ['有灯塔在，船就不会迷路。', '可那阵怪雾……到底是从哪儿来的呢？'] },
    ],
    dialogNight: ['夜里的灯塔最漂亮了。', '光束扫过海面的时候，偶尔能看到跃出水面的宝可梦。'],
    dialog: ['灯塔的光能照到很远的海面。', '可最近，海上起了灯也照不透的雾……'],
  },
  {
    id: 'vendor-fish',
    name: '鱼贩 阿美',
    title: '港湾大市场',
    appearance: { look: 'vendor' },
    service: { kind: 'shop', shop: 'harbor-sea' },
    dialog: ['新鲜的海货！今早刚上岸的！', '渔船偶尔会从海底捞上来闪闪发亮的石头，要看看吗？'],
  },
  {
    id: 'vendor-fruit',
    name: '果贩 老吴',
    title: '港湾大市场',
    appearance: { look: 'vendor', palette: { jacket: '#e89a3c', hair: '#6a6a6a' }, style: { hair: 'bald', apron: true }, accent: '#6fae4a' },
    service: { kind: 'shop', shop: 'harbor-fruit' },
    dialog: ['树果能帮宝可梦恢复体力。', '橙橙果最受欢迎，要来几个吗？'],
  },
  {
    id: 'vendor-tools',
    name: '杂货商 阿强',
    title: '港湾大市场',
    appearance: { look: 'vendor', palette: { jacket: '#5a6e8a' }, style: { hat: 'bandana' } },
    service: { kind: 'shop', shop: 'harbor-tools' },
    dialog: ['绳子、灯笼、钓线，出海要用的东西这里都有。', '训练家的话，精灵球也备着呢。'],
  },
  {
    id: 'vendor-tms',
    name: '摊主 阿岚',
    title: '港湾大市场',
    appearance: { look: 'vendor', palette: { jacket: '#c36fd6', hair: '#2b2b3b' }, style: { hair: 'long' }, accent: '#f2c14e' },
    service: { kind: 'shop', shop: 'harbor-tms' },
    dialog: ['招式学习器能反复使用，买一张就够了！', '更厉害的？听说巢穴头目身边常有遗落的学习器……'],
  },
  {
    // 计划文档 §6：想起招式的人（港湾大市场，港湾市没有宝可梦中心）
    id: 'move-reminder-harbor',
    name: '回想婆婆 忆婆',
    title: '想起招式的人',
    appearance: { look: 'elder', palette: { jacket: '#5a8a9a', hair: '#d8d4cc' }, style: { hair: 'long' } },
    service: { kind: 'recall' },
    dialog: ['我老伴在翠澜镇也做这行。', '心之鳞片或 1000 円，帮你的宝可梦想起遗忘的招式。'],
  },
  // ———————————————————————— 幻影之森 · 伪装的索罗亚（M1-14） ————————————————————————
  {
    id: 'zorua-disguise',
    name: '迷路的小女孩',
    title: '？？？',
    appearance: { look: 'child-f', palette: { jacket: '#3a2a55', hair: '#1f1f2a' }, style: { hair: 'long' }, accent: '#d23a5a' },
    schedule: [{ from: 0, to: 24, at: { island: 'sprout', position: [-320, -330], yaw: 0 }, activity: { kind: 'stand' } }],
    showIf: ['zorua-quest-start'],
    hideIf: ['zorua-quest-done'],
    vanishInstantly: true,
    dialogByQuest: [
      { questId: 'side-zorua-forest', when: 'active', requires: ['zorua-revealed'], dialog: [], story: 'zorua-retry' },
      {
        questId: 'side-zorua-forest',
        when: 'active',
        dialog: ['……你是跟着脚印来的吗？', '嘻嘻，这片森林里只有我一个人哦。', '那你猜猜看——我是谁？'],
        setFlags: ['zorua-revealed'],
        story: 'zorua-reveal',
      },
    ],
    dialog: ['……'],
  },
  {
    id: 'lost-item-sailor',
    name: '粗心水手 阿福',
    title: '水手',
    appearance: { look: 'sailor', palette: { jacket: '#8a5a36' } },
    activity: { kind: 'wander', radius: 1.2 },
    dialog: ['奇怪，我明明放在这里的……', '算了，也许是被哪只宝可梦叼走了吧。'],
  },
];
