/**
 * M2 · 碧潮群岛 NPC（碧潮镇 / 矿石镇 / 火山镇 / 温泉乡 + 各室内 + 野外剧情人物）。
 * 室内固定位 NPC（无 schedule）的位置写在 config/interiors/tide.ts 的 `npcs`。
 * 人物造型为程序化占位（M2-19 决议），手工人物模型到位后按 look 替换。
 */
import type { NpcDef } from '@/systems/npcs';

const PI = Math.PI;

export const TIDE_NPCS: NpcDef[] = [
  // ———————————————————————————— 碧潮道馆 ————————————————————————————
  {
    id: 'gym-azure-guide',
    name: '道馆向导',
    title: '碧潮道馆',
    appearance: { look: 'guide', palette: { cap: '#3f7a3a', jacket: '#3f7a3a' } },
    dialogByQuest: [
      { questId: 'main-gym-azure', when: 'active', dialog: ['嘿，未来的冠军！欢迎来到碧潮道馆！', '叶岚用的是草属性宝可梦。火、飞行、冰、虫和毒属性的招式都很有效！', '小心她的王牌斗笠菇——它会格斗招式，岩石和冰属性的伙伴要当心。', '碧潮群岛的三座道馆可以按任意顺序挑战：你拿到的徽章越多，馆主们就会拿出越认真的队伍。'] },
      { questId: 'main-gym-azure', when: 'completed', dialog: ['漂亮！古森的认可到手了！', '有了这枚徽章，野外的藤蔓再也挡不住你了。'] },
    ],
    dialog: ['欢迎来到碧潮道馆！'],
  },
  {
    id: 'yelan',
    name: '叶岚',
    title: '碧潮道馆馆主',
    appearance: { look: 'leader-grass' },
    trainer: 'gym-azure-leader',
    dialogByQuest: [{ questId: 'main-gym-azure', when: 'completed', dialog: ['藤蔓挡路的时候，记得用「居合劈」。', '古森北面的神龛，也许藏着异变的线索。'] }],
    dialog: ['古森在注视着你。'],
  },
  {
    id: 'gym-azure-trainer-1',
    name: '阿蕨',
    title: '园艺家',
    appearance: { look: 'camper', palette: { jacket: '#5d9a3e', cap: '#3f7a3a' } },
    trainer: 'gym-azure-1',
    dialog: ['草属性怕火、怕飞行、怕冰，也怕虫和毒。', '可叶岚大人的斗笠菇会格斗招式，岩石属性别大意。'],
  },
  {
    id: 'gym-azure-trainer-2',
    name: '小苔',
    title: '迷你裙',
    appearance: { look: 'lass', palette: { jacket: '#8fc06a' } },
    trainer: 'gym-azure-2',
    dialog: ['叶岚大人在树洞前等你。', '她的王牌会「寄生种子」，拖久了会很难缠。'],
  },
  // ———————————————————————————— 碧潮镇 ————————————————————————————
  {
    id: 'tide-elder',
    name: '树语长老',
    title: '碧潮镇长老',
    appearance: { look: 'elder', palette: { jacket: '#3f7a3a', pants: '#5a4028' }, style: { hair: 'bald', beard: true, coat: 'long' } },
    dialogByQuest: [
      {
        questId: 'side-anomaly-survivor',
        when: 'available',
        setFlags: ['survivor-1-heard'],
        dialog: [
          '……你也在追查异变？那就坐下吧，听老头子讲讲。',
          '五十年前，群岛也出过一次异变。那年古森一夜之间长高了一倍，根须钻进了每一口井。',
          '我那时和你一样大。一道紫光从中央高原升起，第二天，镇上一半的宝可梦都不见了。',
          '当年活下来的人不多了。矿石镇有个退休的老矿工，温泉乡的旅馆里还有位老婆婆。',
          '去听听他们怎么说吧。三个人的记忆拼在一起，也许就是真相的一角。',
        ],
      },
      { questId: 'side-anomaly-survivor', when: 'active', dialog: ['矿石镇的老矿工叫石根老爹，温泉乡旅馆里的是汤婆婆。', '他们记得的，比我多。'] },
      { questId: 'main-gym-azure', when: 'active', dialog: ['巨树下的道馆，是叶岚那孩子守着的。', '她听得懂树的话。你若能让她点头，古森就会为你让路。'] },
    ],
    dialog: ['古森的根，连着整座岛。', '岛上发生什么，树都知道。'],
  },
  {
    id: 'forest-child-mom',
    name: '小芽妈妈',
    title: '碧潮镇居民',
    appearance: { look: 'villager-f', palette: { jacket: '#c8a050' } },
    schedule: [{ from: 6, to: 22, at: { island: 'tide', position: [-452, 40], yaw: PI }, activity: { kind: 'wander', radius: 2 } }],
    dialogByQuest: [
      { questId: 'side-forest-child', when: 'completed', dialog: ['小芽现在一步都不肯离开我了，哈哈。', '真的谢谢你。'] },
      { questId: 'side-forest-child', when: 'active', requires: ['forest-child-found'], setFlags: ['forest-child-done'], dialog: ['小芽！你回来了！', '……谢谢你，真的谢谢你！', '这是我家院子里结的「奇迹种子」，让草属性的伙伴带着吧。'] },
      { questId: 'side-forest-child', when: 'active', dialog: ['小芽说要去古森里找会发光的蘑菇……', '他总在北边的大池塘附近玩。拜托了！'] },
      {
        questId: 'side-forest-child',
        when: 'available',
        setFlags: ['forest-child-start'],
        dialog: ['你是训练家吧？求求你帮帮我！', '我家小芽一早就跑进碧潮古森了，到现在都没回来。', '古森里雾大，路会绕回原地……他一定是迷路了。', '他说想去找会发光的蘑菇，大概在北边的池塘一带。拜托你了！'],
      },
    ],
    dialog: ['碧潮镇的房子都搭在巨树的根上。', '下雨的时候，整座镇子都闻得到青苔的味道。'],
  },
  {
    id: 'lost-child',
    name: '小芽',
    title: '迷路的孩子',
    appearance: { look: 'child-m', palette: { jacket: '#8fc06a' } },
    showIf: ['forest-child-start'],
    hideIf: ['forest-child-found'],
    vanishInstantly: true,
    schedule: [{ from: 0, to: 24, at: { island: 'tide', position: [-302, -302], yaw: PI / 2 }, activity: { kind: 'stand' } }],
    dialogByQuest: [
      {
        questId: 'side-forest-child',
        when: 'active',
        setFlags: ['forest-child-found'],
        dialog: ['呜……你、你是谁？', '妈妈让你来找我的？', '我、我只是想看会发光的蘑菇……然后就找不到路了。', '……嗯，我跟你回去。你走前面好不好？'],
      },
    ],
    dialog: ['……'],
  },
  {
    id: 'forest-child-home',
    name: '小芽',
    title: '碧潮镇的孩子',
    appearance: { look: 'child-m', palette: { jacket: '#8fc06a' } },
    showIf: ['forest-child-found'],
    schedule: [{ from: 7, to: 20, at: { island: 'tide', position: [-448, 44], yaw: PI }, activity: { kind: 'wander', radius: 1.5 } }],
    dialog: ['我再也不一个人进古森了！', '……不过发光的蘑菇真的好漂亮。'],
  },
  {
    id: 'tide-villager-1',
    name: '阿根',
    title: '碧潮镇居民',
    appearance: { look: 'villager-m', palette: { jacket: '#5d8f3e' } },
    schedule: [{ from: 7, to: 20, at: { island: 'tide', position: [-480, 96], yaw: 0 }, activity: { kind: 'wander', radius: 3 } }],
    dialog: ['那棵巨树？听说比群岛上任何一座房子都老。', '长老就住在巨树上的树屋里。'],
    dialogNight: ['夜里树屋的灯一盏盏亮起来，像萤火虫一样。'],
  },
  {
    id: 'tide-ferry-clerk',
    name: '渡船员小潮',
    title: '碧潮镇码头',
    appearance: { look: 'sailor' },
    schedule: [{ from: 0, to: 24, at: { island: 'tide', position: [-592, 26], yaw: PI / 2 } }],
    dialog: ['这里是碧潮镇码头。', '有渡船船票的话，在码头边的渡船处就能坐船回港湾市。'],
  },
  // ———————————————————————————— 矿石道馆 / 矿石镇 ————————————————————————————
  {
    id: 'gym-ore-guide',
    name: '道馆向导',
    title: '矿石道馆',
    appearance: { look: 'guide', palette: { cap: '#c08a3e', jacket: '#c08a3e' } },
    dialogByQuest: [
      { questId: 'main-gym-ore', when: 'active', dialog: ['嘿，未来的冠军！欢迎来到矿石道馆！', '岩磊用的是岩石属性宝可梦。水、草、格斗、地面、钢属性的招式都很有效！', '他的大岩蛇有「结实」特性，满体力时一击打不倒——多打一下就行。'] },
      { questId: 'main-gym-ore', when: 'completed', dialog: ['你把岩磊的石头敲碎了！痛快！'] },
    ],
    dialog: ['欢迎来到矿石道馆！'],
  },
  {
    id: 'yanlei',
    name: '岩磊',
    title: '矿石道馆馆主',
    appearance: { look: 'leader-rock' },
    trainer: 'gym-ore-leader',
    dialogByQuest: [{ questId: 'main-gym-ore', when: 'completed', dialog: ['矿洞的事多亏了你。', '在野外看到挡路的巨石，记得用「怪力」推开。'] }],
    dialog: ['石头不会说谎！'],
  },
  {
    id: 'gym-ore-trainer-1',
    name: '石头',
    title: '矿工',
    appearance: { look: 'miner' },
    trainer: 'gym-ore-1',
    dialog: ['岩石属性怕水、草、格斗、地面和钢。', '岩磊大人的大岩蛇特别硬，有「结实」特性，一击打不倒。'],
  },
  {
    id: 'gym-ore-trainer-2',
    name: '砾砾',
    title: '登山女',
    appearance: { look: 'hiker', palette: { hair: '#7a4a2a', jacket: '#c08a3e' }, style: { hair: 'pony', beard: false } },
    trainer: 'gym-ore-2',
    dialog: ['岩磊大人说话像打雷，其实心特别软。'],
  },
  {
    id: 'ore-foreman',
    name: '老铁',
    title: '矿洞工头',
    appearance: { look: 'miner', palette: { jacket: '#8a6440' }, style: { beard: true } },
    dialogByQuest: [
      { questId: 'main-mine-anomaly', when: 'completed', dialog: ['异变碎片……这东西还是你带着吧。', '矿洞我会先封起来，等你们查清楚再说。'] },
      {
        questId: 'main-mine-anomaly',
        when: 'active',
        requires: ['mine-anomaly-found'],
        setFlags: ['mine-anomaly-reported'],
        dialog: ['你找到了什么？……这颗红色的碎片？', '摸上去烫手……矿里的晶石就是从这东西周围开始变紫的。', '我挖了三十年矿，从没见过这种东西。', '这碎片你收好。木兰博士要是在研究异变，一定用得上。'],
      },
      { questId: 'main-mine-anomaly', when: 'active', requires: ['mine-anomaly-start'], dialog: ['矿洞就在镇子北边，顺着矿车轨道走。', '深层矿脉的西侧，晶石变紫的地方就是了。'] },
      {
        questId: 'main-mine-anomaly',
        when: 'active',
        setFlags: ['mine-anomaly-start'],
        dialog: ['你就是从萌芽群岛来的训练家？正好，帮我个忙。', '矿洞深处最近不对劲——晶石变成了紫色，宝可梦也变得暴躁。', '工人们都不敢下去了。你去深层矿脉看看，到底是什么在作怪。'],
      },
    ],
    dialog: ['矿石镇靠矿吃饭。', '矿洞一停，全镇都得饿肚子。'],
  },
  {
    id: 'foreman-wife',
    name: '铁嫂',
    title: '工头的妻子',
    appearance: { look: 'villager-f', palette: { jacket: '#b98a5a' }, style: { apron: true } },
    dialogByQuest: [
      { questId: 'side-mine-rescue', when: 'completed', dialog: ['石根那小子回来就睡了一整天。', '你可是我们家的大恩人！'] },
      {
        questId: 'side-mine-rescue',
        when: 'active',
        requires: ['mine-miner-rescued'],
        setFlags: ['mine-rescue-done'],
        dialog: ['石根回来了！我听见他在外头喊娘了！', '……谢谢你。真的谢谢你。', '这是我们矿工代代相传的本事——「怪力」。', '让宝可梦把力气使出来，再大的石头也推得动。赭石丘陵的骨冢、矿洞深处的石室，都去看看吧。'],
      },
      { questId: 'side-mine-rescue', when: 'active', dialog: ['石根就在深层矿脉的东边，塌方的地方。', '拜托你，快一点……'] },
      {
        questId: 'side-mine-rescue',
        when: 'available',
        setFlags: ['mine-rescue-start'],
        dialog: ['你是训练家吗？求你救救我侄子石根！', '他昨天一个人下矿，深层矿脉塌方了，到现在都没出来。', '塌方那边有一条大岩蛇守着，谁都过不去……', '求你了，帮帮他！'],
      },
    ],
    dialog: ['我家那口子整天泡在矿里。', '饭都凉了还不回来。'],
  },
  {
    id: 'trapped-miner',
    name: '石根',
    title: '被困的矿工',
    appearance: { look: 'miner', palette: { jacket: '#d08a4a' } },
    showIf: ['mine-rescue-start'],
    hideIf: ['mine-rescue-done'],
    dialogByQuest: [
      { questId: 'side-mine-rescue', when: 'active', requires: ['mine-miner-rescued'], dialog: ['得救了……谢谢你！', '我这就回家，你也去跟我婶说一声吧！'] },
      { questId: 'side-mine-rescue', when: 'active', dialog: ['救、救命……', '大岩蛇就在前面，我动都不敢动……'] },
    ],
    dialog: ['……'],
  },
  {
    id: 'old-miner',
    name: '石根老爹',
    title: '退休矿工',
    appearance: { look: 'miner', palette: { hair: '#d8d4cc', jacket: '#7a6450' }, style: { beard: true, stoop: 0.18, cane: true } },
    schedule: [{ from: 7, to: 19, at: { island: 'tide', position: [70, 214], yaw: PI }, activity: { kind: 'stand' } }],
    dialogByQuest: [
      {
        questId: 'side-anomaly-survivor',
        when: 'active',
        unless: ['survivor-2-heard'],
        setFlags: ['survivor-2-heard'],
        dialog: [
          '长老让你来的？……唉，那年的事啊。',
          '异变那天，我正在矿洞最底下。整座山都在嗡嗡响，岩壁上的晶石一块接一块亮成紫色。',
          '我们往外跑的时候，看见一块石板从塌方里露出来，上面刻着看不懂的字。',
          '后来那一层就封了。可我一直记得——石板上画着一个巨大的、石头做的人。',
        ],
      },
      { questId: 'side-anomaly-survivor', when: 'active', dialog: ['温泉乡的汤婆婆，那天在高原上。', '她看到的，比我多。'] },
    ],
    dialog: ['我这把老骨头，下不了矿喽。', '年轻人，挖矿要戴好头盔。'],
  },
  {
    id: 'ore-villager-1',
    name: '小矿',
    title: '矿石镇的孩子',
    appearance: { look: 'child-m', palette: { cap: '#f2c230', jacket: '#c07a3a' }, style: { hat: 'cap' } },
    schedule: [{ from: 8, to: 19, at: { island: 'tide', position: [60, 270], yaw: 0 }, activity: { kind: 'wander', radius: 3 } }],
    dialog: ['我长大了也要当矿工！', '岩磊叔叔一拳能把石头打碎！'],
  },
  // ———————————————————————————— 碧焰道馆 / 火山镇 ————————————————————————————
  {
    id: 'gym-flame-guide',
    name: '道馆向导',
    title: '碧焰道馆',
    appearance: { look: 'guide', palette: { cap: '#c8502a', jacket: '#c8502a' } },
    dialogByQuest: [
      { questId: 'main-gym-flame', when: 'active', dialog: ['嘿，未来的冠军！欢迎来到碧焰道馆！', '炎棘用的是火属性宝可梦。水、地面、岩石属性的招式都很有效！', '熔岩沟千万别靠近，沿着中间的玄武岩栈道走。'] },
      { questId: 'main-gym-flame', when: 'completed', dialog: ['你连炎棘的火都压下去了！'] },
    ],
    dialog: ['欢迎来到碧焰道馆！'],
  },
  {
    id: 'yanji',
    name: '炎棘',
    title: '碧焰道馆馆主',
    appearance: { look: 'leader-fire' },
    trainer: 'gym-flame-leader',
    dialogByQuest: [{ questId: 'main-gym-flame', when: 'completed', dialog: ['火山洞窟漆黑一片，「闪光」能照亮它。', '地热的事，观测站的老秦一直在查。'] }],
    dialog: ['……'],
  },
  {
    id: 'gym-flame-trainer-1',
    name: '阿炭',
    title: '吹火人',
    appearance: { look: 'youngster', palette: { jacket: '#c8502a', shirt: '#f0742a', cap: '#2c2428' } },
    trainer: 'gym-flame-1',
    dialog: ['火属性怕水、地面和岩石。', '炎棘大人的煤炭龟会放烟幕，命中率要留意。'],
  },
  {
    id: 'gym-flame-trainer-2',
    name: '焰焰',
    title: '迷你裙',
    appearance: { look: 'lass', palette: { jacket: '#f0742a', hair: '#c8502a' } },
    trainer: 'gym-flame-2',
    dialog: ['炎棘大人从不笑，但她的火焰很温柔。'],
  },
  {
    id: 'obs-chief',
    name: '老秦',
    title: '地热观测站站长',
    appearance: { look: 'researcher', palette: { hair: '#c8c4bc' }, style: { beard: true } },
    dialogByQuest: [
      { questId: 'main-volcano-heat', when: 'completed', dialog: ['地热读数已经回落到正常范围了。', '火山口那条路也能走了，热浪散了。'] },
      {
        questId: 'main-volcano-heat',
        when: 'active',
        requires: ['volcano-heat-source-found'],
        setFlags: ['volcano-heat-cleared'],
        dialog: ['你回来了！读数刚才突然降下来了——你在核心做了什么？', '……一颗橙色的碎片？和矿石镇挖出来的红碎片很像。', '异变能量在往地下灌……它把地热「推」高了。', '这碎片你拿着吧。火山口的热浪散了，那边的路也通了。'],
      },
      { questId: 'main-volcano-heat', when: 'active', requires: ['volcano-heat-start'], dialog: ['火山洞窟在镇子东北边。', '洞里很黑，碧焰道馆的徽章能让宝可梦使出「闪光」。', '地热核心在最深处——小心，那里的宝可梦都被热浪逼疯了。'] },
      {
        questId: 'main-volcano-heat',
        when: 'active',
        setFlags: ['volcano-heat-start'],
        dialog: ['你看这张图——这是火山镇一个月来的地热读数。', '一直在往上涨，而且不是自然的涨法。像是有东西从地底往上推。', '火山口的热浪已经烫得没人靠近了。', '能不能帮我去火山洞窟最深处的地热核心看看？那里是热源。'],
      },
    ],
    dialog: ['火山是活的。', '它呼吸，它做梦——我们只是在旁边记录。'],
  },
  {
    id: 'obs-aide',
    name: '研究员小焰',
    title: '观测员',
    appearance: { look: 'researcher', palette: { hair: '#c8502a' }, style: { hair: 'pony' } },
    dialog: ['地震仪的针一直在抖。', '站长已经三天没睡了。'],
  },
  {
    id: 'flame-villager-1',
    name: '阿岩',
    title: '火山镇居民',
    appearance: { look: 'villager-m', palette: { jacket: '#3b3640' } },
    schedule: [{ from: 7, to: 21, at: { island: 'tide', position: [560, 100], yaw: 0 }, activity: { kind: 'wander', radius: 3 } }],
    dialog: ['火山镇的房子都是黑曜石砌的。', '不怕火，冬天还特别暖和。'],
  },
  // ———————————————————————————— 温泉乡 ————————————————————————————
  {
    id: 'spring-breeder-lady',
    name: '暖婆婆',
    title: '培育屋',
    appearance: { look: 'kimono-f', palette: { hair: '#d8d4cc', jacket: '#e07a8a' }, style: { stoop: 0.12 } },
    service: { kind: 'breeder' },
    dialogByQuest: [
      { questId: 'side-volcano-egg', when: 'completed', dialog: ['燃烧虫长得好吗？', '它是在温泉的热气里出生的，最喜欢暖和的地方。'] },
      {
        questId: 'side-volcano-egg',
        when: 'active',
        setFlags: ['volcano-egg-hatched'],
        dialog: ['哎呀，这枚蛋好烫！是从火山洞窟里捡的？', '放进温泉水里温一温……你看，它在动！', '……孵出来了！是燃烧虫！', '它第一眼看见的就是你。好好照顾它吧。'],
      },
    ],
    dialog: ['这里是温泉乡的培育屋。', '温泉的热气对宝可梦的蛋最好了。'],
  },
  {
    id: 'spring-breeder-man',
    name: '暖爷爷',
    title: '培育屋',
    appearance: { look: 'elder', palette: { jacket: '#4a5a6a' }, style: { hair: 'bald', coat: 'long', cane: false } },
    dialog: ['火山洞窟里偶尔能捡到宝可梦的蛋。', '老太婆最会孵蛋了，捡到了就拿来吧。'],
  },
  {
    id: 'inn-owner',
    name: '汤老板',
    title: '汤之庭老板',
    appearance: { look: 'villager-m', palette: { jacket: '#3f6db5' }, style: { apron: true } },
    dialogByQuest: [
      { questId: 'side-hot-spring-source', when: 'completed', dialog: ['温泉又热乎起来了！客人们都回来了！', '外面的露天温泉随便泡，不收钱！'] },
      {
        questId: 'side-hot-spring-source',
        when: 'active',
        requires: ['cleared:spring-source-rock'],
        setFlags: ['spring-source-done'],
        dialog: ['温泉……温泉热起来了！是你把源头打通的？', '太感谢了！这块「火之石」是从源头附近挖到的，送给你。', '以后外面的露天温泉，你随时来泡，一分钱都不要！'],
      },
      { questId: 'side-hot-spring-source', when: 'active', dialog: ['泉眼在溪谷上游，顺着温泉溪往北走。', '那块落石太大了，得用「碎岩」才撞得开。'] },
      {
        questId: 'side-hot-spring-source',
        when: 'available',
        setFlags: ['spring-source-start'],
        dialog: ['欢迎光临汤之庭……唉，可惜温泉不热了。', '上游的泉眼被一块大落石堵住了，热水流不下来。', '要是有人能撞开那块石头就好了……听说异变遗迹里的守护者，守着一种能撞碎岩石的力量。'],
      },
    ],
    dialog: ['欢迎光临汤之庭！', '客房在大堂右边，累了就去休息吧。'],
  },
  {
    id: 'inn-grandma',
    name: '汤婆婆',
    title: '异变幸存者',
    appearance: { look: 'elder', palette: { jacket: '#3f4a5a' } },
    dialogByQuest: [
      {
        questId: 'main-hot-spring-info',
        when: 'active',
        requires: ['arrived-spring-village'],
        dialog: [],
        story: 'hot-spring-history',
      },
      {
        questId: 'side-anomaly-survivor',
        when: 'active',
        requires: ['survivor-1-heard', 'survivor-2-heard'],
        setFlags: ['survivor-3-heard', 'anomaly-survivor-done'],
        dialog: [
          '长老和石根都跟你讲过了？那我也说说吧。',
          '异变那天，我就在中央高原上采药。紫光从地底冒出来，在天上结成一个罩子。',
          '罩子里有个石头巨人，睁开眼睛看了我一下……然后光就收回去了。',
          '我一直觉得，它不是在害人，是在「封」住什么。',
          '……奇怪，我说着说着，手心里多了块亮晶晶的东西。拿去吧，这是我们三个人的记忆。',
        ],
      },
      { questId: 'side-anomaly-survivor', when: 'active', dialog: ['先去听听长老和石根老爹怎么说吧。', '老婆子的记性，要别人提个头才想得起来。'] },
    ],
    dialog: ['年轻人，泡完温泉再走吧。', '人老了，就爱坐在这里看客人来来去去。'],
  },
  {
    id: 'spring-captain',
    name: '船老大',
    title: '温泉乡码头',
    appearance: { look: 'sailor', palette: { jacket: '#c8402e' }, style: { beard: true } },
    schedule: [{ from: 0, to: 24, at: { island: 'tide', position: [560, 640], yaw: PI / 2 } }],
    dialog: ['碧潮—雷鸣海域最近洋流很乱，航线暂时关闭了。', '等海况好了，我第一个开船。'],
  },
  {
    id: 'spring-villager-1',
    name: '阿暖',
    title: '温泉乡居民',
    appearance: { look: 'kimono-f' },
    schedule: [{ from: 8, to: 21, at: { island: 'tide', position: [440, 530], yaw: PI }, activity: { kind: 'wander', radius: 3 } }],
    dialogByQuest: [{ questId: 'side-hot-spring-source', when: 'completed', dialog: ['温泉又热了！泡完浑身轻飘飘的。', '宝可梦们也最喜欢泡温泉了。'] }],
    dialog: ['最近温泉温吞吞的，泡着一点也不舒服。', '汤之庭的老板愁得头发都白了。'],
  },
  // ———————————————————————————— 异变遗迹 ————————————————————————————
  {
    id: 'ruins-scholar',
    name: '考古学家洛文',
    title: '遗迹学者',
    appearance: { look: 'professor', palette: { hair: '#5a4a3a', jacket: '#8a7a5a' }, style: { hat: 'bucket', bag: true, coat: 'long', glasses: true } },
    schedule: [{ from: 0, to: 24, at: { island: 'tide', position: [30, -392], yaw: PI } }],
    dialogByQuest: [
      { questId: 'main-ruins-seal', when: 'active', unless: ['ruins-seal-open'], dialog: ['这层紫色的结界……和群岛各处的异变是同一种能量。', '石碑上写着：「三枚岛之证聚首之时，门将开启。」', '岛之证——会不会就是道馆的徽章？'] },
      { questId: 'main-ruins-boss', when: 'active', dialog: ['你进去过了？里面有……守护者？', '小心。古代人把它留在这里，一定有原因。'] },
      { questId: 'main-ruins-boss', when: 'completed', dialog: ['守护者认可了你……', '我会把壁画全部抄下来。异变的真相，就藏在这些图案里。'] },
    ],
    dialog: ['这座遗迹比群岛上任何一座城镇都古老。', '没有结界的时候，我一定要进去看看。'],
  },
];
